import os
import json
import hashlib
from web3 import Web3

def record_level_completion_on_chain(member_no, path_name, level):
    """
    Records a level completion hash to the smart contract on the Sepolia network.
    
    Hash is generated as SHA256(member_no + path_name + level)
    """
    
    # Validate inputs as requested by the user
    if not member_no or not path_name or not level:
        print(f"Skipping blockchain record: Missing required data (member_no={member_no}, path_name={path_name}, level={level})")
        return False
        
    # Check if we have the necessary credentials
    rpc_url = os.environ.get("SEPOLIA_RPC_URL")
    private_key = os.environ.get("WALLET_PRIVATE_KEY")
    contract_address = os.environ.get("LEVEL_TRACKER_CONTRACT_ADDRESS")
    
    if not (rpc_url and private_key and contract_address):
        print("Blockchain settings missing. Skipping level tracking on chain.")
        return False
        
    try:
        # Load the ABI
        abi_path = os.path.join(os.path.dirname(__file__), "level_tracker_abi.json")
        if not os.path.exists(abi_path):
            print(f"Contract ABI not found at {abi_path}. Ensure it is generated by the deploy script.")
            return False
            
        with open(abi_path, "r") as f:
            abi = json.load(f)

        # Connect to network
        w3 = Web3(Web3.HTTPProvider(rpc_url))
        if not w3.is_connected():
            print("Failed to connect to the Sepolia RPC URL.")
            return False

        account = w3.eth.account.from_key(private_key)
        contract = w3.eth.contract(address=contract_address, abi=abi)

        # Generate the hash
        raw_string = f"{member_no}{path_name}{level}"
        completion_hash = hashlib.sha256(raw_string.encode('utf-8')).digest()

        # Build transaction using the 'pending' nonce so we can send multiple quickly
        nonce = w3.eth.get_transaction_count(account.address, 'pending')
        
        # We use build_transaction to prepare it before signing
        transaction = contract.functions.recordLevel(completion_hash).build_transaction({
            'chainId': 11155111, # Sepolia
            'gas': 2000000,      # A safe limit, will probably use less
            'gasPrice': w3.eth.gas_price,
            'nonce': nonce,
            'from': account.address
        })

        # Sign transaction
        signed_txn = w3.eth.account.sign_transaction(transaction, private_key=private_key)

        # Send transaction
        tx_hash = w3.eth.send_raw_transaction(signed_txn.rawTransaction)
        print(f"Sent blockchain transaction! Hash: {w3.to_hex(tx_hash)}")
        
        # For a web app, we generally don't want to wait synchronously for the transaction to be mined
        # because it can take 15+ seconds. We just return True that it was sent.
        return True

    except Exception as e:
        print(f"An error occurred while tracking level to blockchain: {e}")
        return False
