"""fix meetings id auto increment

Revision ID: 02ee44fa58f8
Revises: 785f9339c40e
Create Date: 2025-12-30 10:59:45.277166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ee44fa58f8'
down_revision = '785f9339c40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE Meetings MODIFY id INT NOT NULL AUTO_INCREMENT")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE Meetings MODIFY id INT NOT NULL")
    # ### end Alembic commands ###
