"""allow duration min to be nullable

Revision ID: 032e75c6fedf
Revises: 7064d9c78574
Create Date: 2025-11-14 22:25:14.503243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '032e75c6fedf'
down_revision = '7064d9c78574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.alter_column('Duration_Min',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.alter_column('Duration_Min',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
