"""actually drop meeting_number columns

Revision ID: 07c3adfd0a6a
Revises: 8ca4df2d75ce
Create Date: 2026-02-12 20:41:58.051843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07c3adfd0a6a'
down_revision = '8ca4df2d75ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.drop_column('Meeting_Number')

    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.drop_column('meeting_number')

    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.drop_column('meeting_number')

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_column('meeting_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_number', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_number', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_number', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Meeting_Number', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
