"""add member_no phone dtm avatar_url bio to users

Revision ID: 08e99002e832
Revises: b039865b5938
Create Date: 2026-01-17 01:02:35.996619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e99002e832'
down_revision = 'b039865b5938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('Users')]

    with op.batch_alter_table('Users', schema=None) as batch_op:
        if 'member_no' not in columns:
            batch_op.add_column(sa.Column('member_no', sa.String(length=50), nullable=True))
        if 'phone' not in columns:
            batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        if 'dtm' not in columns:
            batch_op.add_column(sa.Column('dtm', sa.Boolean(), nullable=False))
        if 'avatar_url' not in columns:
            batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))
        if 'bio' not in columns:
            batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('dtm')
        batch_op.drop_column('phone')
        batch_op.drop_column('member_no')

    # ### end Alembic commands ###
