"""rename GE_Style to ge_mode and change its type to int

Revision ID: 0d317a79108e
Revises: dd8425cc0f23
Create Date: 2025-12-30 16:02:09.971844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d317a79108e'
down_revision = 'dd8425cc0f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Meetings', sa.Column('ge_mode', sa.Integer(), nullable=True))
    
    # Data migration
    op.execute("UPDATE Meetings SET ge_mode = 0 WHERE GE_Style IN ('One shot', 'deferred')")
    op.execute("UPDATE Meetings SET ge_mode = 1 WHERE GE_Style = 'Multiple shots'")
    
    op.drop_column('Meetings', 'GE_Style')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Meetings', sa.Column('GE_Style', mysql.VARCHAR(length=20), server_default=sa.text("'One shot'"), nullable=True))
    
    # Data migration back
    op.execute("UPDATE Meetings SET GE_Style = 'One shot' WHERE ge_mode = 0")
    op.execute("UPDATE Meetings SET GE_Style = 'Multiple shots' WHERE ge_mode = 1")
    
    op.drop_column('Meetings', 'ge_mode')
    # ### end Alembic commands ###
