"""add question score and comments columns to vote model

Revision ID: 10445870672c
Revises: d2039c1c5357
Create Date: 2026-01-10 16:56:26.349495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10445870672c'
down_revision = 'd2039c1c5357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_column('comments')
        batch_op.drop_column('score')
        batch_op.drop_column('question')

    # ### end Alembic commands ###
