"""Add associated_role

Revision ID: 14b1f51a5a3f
Revises: 4500d155515b
Create Date: 2026-06-15 00:01:56.553727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b1f51a5a3f'
down_revision = '4500d155515b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_award_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('associated_role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_award_configs', schema=None) as batch_op:
        batch_op.drop_column('associated_role')
    # ### end Alembic commands ###
