"""Initial installation

Revision ID: 14e9302a2d45
Revises: 
Create Date: 2026-01-13 17:19:06.046216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14e9302a2d45'
down_revision = None
branch_labels = None
depends_on = None


def _drop_all_tables():
    """Helper function to drop all tables with foreign key checks disabled."""
    # Disable foreign key checks to allow dropping tables in any order
    op.execute('SET FOREIGN_KEY_CHECKS=0')
    
    # Drop tables if they exist
    op.execute('DROP TABLE IF EXISTS waitlists')
    op.execute('DROP TABLE IF EXISTS Media')
    op.execute('DROP TABLE IF EXISTS roster_roles')
    op.execute('DROP TABLE IF EXISTS Session_Logs')
    op.execute('DROP TABLE IF EXISTS votes')
    op.execute('DROP TABLE IF EXISTS roster')
    op.execute('DROP TABLE IF EXISTS pathway_projects')
    op.execute('DROP TABLE IF EXISTS achievements')
    op.execute('DROP TABLE IF EXISTS Users')
    op.execute('DROP TABLE IF EXISTS Session_Types')
    op.execute('DROP TABLE IF EXISTS Meetings')
    op.execute('DROP TABLE IF EXISTS roles')
    op.execute('DROP TABLE IF EXISTS pathways')
    op.execute('DROP TABLE IF EXISTS level_roles')
    op.execute('DROP TABLE IF EXISTS Projects')
    op.execute('DROP TABLE IF EXISTS Contacts')
    
    # Re-enable foreign key checks
    op.execute('SET FOREIGN_KEY_CHECKS=1')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop all existing tables first
    _drop_all_tables()
    
    op.create_table('Contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Type', sa.String(length=50), nullable=False),
    sa.Column('Club', sa.String(length=100), nullable=True),
    sa.Column('Date_Created', sa.Date(), nullable=True),
    sa.Column('Completed_Paths', sa.String(length=255), nullable=True),
    sa.Column('DTM', sa.Boolean(), nullable=True),
    sa.Column('Phone_Number', sa.String(length=50), nullable=True),
    sa.Column('Bio', sa.Text(), nullable=True),
    sa.Column('Member_ID', sa.String(length=50), nullable=True),
    sa.Column('Mentor_ID', sa.Integer(), nullable=True),
    sa.Column('Current_Path', sa.String(length=50), nullable=True),
    sa.Column('Next_Project', sa.String(length=100), nullable=True),
    sa.Column('credentials', sa.String(length=10), nullable=True),
    sa.Column('Avatar_URL', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['Mentor_ID'], ['Contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Member_ID'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Project_Name', sa.String(length=255), nullable=False),
    sa.Column('Format', sa.String(length=50), nullable=True),
    sa.Column('Duration_Min', sa.Integer(), nullable=True),
    sa.Column('Duration_Max', sa.Integer(), nullable=True),
    sa.Column('Introduction', sa.String(length=1000), nullable=True),
    sa.Column('Overview', sa.String(length=1000), nullable=True),
    sa.Column('Purpose', sa.String(length=255), nullable=True),
    sa.Column('Requirements', sa.String(length=500), nullable=True),
    sa.Column('Resources', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('count_required', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pathways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('abbr', sa.String(length=5), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'obsolete', name='pathway_status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('award_category', sa.String(length=30), nullable=True),
    sa.Column('needs_approval', sa.Boolean(), nullable=False),
    sa.Column('is_distinct', sa.Boolean(), nullable=False),
    sa.Column('is_member_only', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('Meeting_Number', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('Meeting_Date', sa.Date(), nullable=True),
    sa.Column('Meeting_Title', sa.String(length=255), nullable=True),
    sa.Column('Subtitle', sa.String(length=255), nullable=True),
    sa.Column('Start_Time', sa.Time(), nullable=True),
    sa.Column('Meeting_Template', sa.String(length=100), nullable=True),
    sa.Column('WOD', sa.String(length=100), nullable=True),
    sa.Column('best_table_topic_id', sa.Integer(), nullable=True),
    sa.Column('best_evaluator_id', sa.Integer(), nullable=True),
    sa.Column('best_speaker_id', sa.Integer(), nullable=True),
    sa.Column('best_role_taker_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('ge_mode', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('unpublished', 'not started', 'running', 'finished', 'cancelled', name='meeting_status'), nullable=False),
    sa.Column('nps', sa.Float(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['best_evaluator_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['best_role_taker_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['best_speaker_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['best_table_topic_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['Media.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Meeting_Number')
    )
    op.create_table('Session_Types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Default_Owner', sa.String(length=255), nullable=True),
    sa.Column('Is_Section', sa.Boolean(), nullable=True),
    sa.Column('Is_Hidden', sa.Boolean(), nullable=True),
    sa.Column('Predefined', sa.Boolean(), nullable=True),
    sa.Column('Valid_for_Project', sa.Boolean(), nullable=True),
    sa.Column('Duration_Min', sa.Integer(), nullable=True),
    sa.Column('Duration_Max', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Title')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Contact_ID', sa.Integer(), nullable=True),
    sa.Column('Pass_Hash', sa.String(length=255), nullable=False),
    sa.Column('Date_Created', sa.Date(), nullable=True),
    sa.Column('Role', sa.String(length=50), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['Contact_ID'], ['Contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Contact_ID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('achievement_type', sa.Enum('level-completion', 'path-completion', 'program-completion', name='achievement_type_enum'), nullable=False),
    sa.Column('path_name', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pathway_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('elective', 'required', 'other', name='pathway_project_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['pathways.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_number', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('ticket', sa.String(length=20), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('contact_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_number', sa.Integer(), nullable=False),
    sa.Column('voter_identifier', sa.String(length=64), nullable=False),
    sa.Column('award_category', sa.Enum('speaker', 'evaluator', 'role-taker', 'table-topic', name='award_category_enum'), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index('idx_meeting_voter', ['meeting_number', 'voter_identifier'], unique=False)

    op.create_table('Session_Logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Meeting_Number', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('Meeting_Seq', sa.Integer(), nullable=True),
    sa.Column('Session_Title', sa.String(length=255), nullable=True),
    sa.Column('Type_ID', sa.Integer(), nullable=False),
    sa.Column('Owner_ID', sa.Integer(), nullable=True),
    sa.Column('credentials', sa.String(length=255), nullable=True),
    sa.Column('Project_ID', sa.Integer(), nullable=True),
    sa.Column('Start_Time', sa.Time(), nullable=True),
    sa.Column('Duration_Min', sa.Integer(), nullable=True),
    sa.Column('Duration_Max', sa.Integer(), nullable=True),
    sa.Column('Notes', sa.String(length=1000), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('project_code', sa.String(length=10), nullable=True),
    sa.Column('pathway', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['Meeting_Number'], ['Meetings.Meeting_Number'], ),
    sa.ForeignKeyConstraint(['Owner_ID'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['Project_ID'], ['Projects.id'], ),
    sa.ForeignKeyConstraint(['Type_ID'], ['Session_Types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roster_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['roster.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roster_id', 'role_id', name='uq_roster_role')
    )
    op.create_table('Media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['Session_Logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waitlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_log_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['session_log_id'], ['Session_Logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_all_tables()
    # ### end Alembic commands ###
