"""Initial installation

Revision ID: 14e9302a2d45
Revises: 
Create Date: 2026-01-13 17:19:06.046216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14e9302a2d45'
down_revision = None
branch_labels = None
depends_on = None


def _drop_all_tables():
    """Helper function to drop all tables with foreign key checks disabled."""
    # Disable foreign key checks to allow dropping tables in any order
    op.execute('SET FOREIGN_KEY_CHECKS=0')
    
    # Drop tables if they exist
    op.execute('DROP TABLE IF EXISTS user_roles')
    op.execute('DROP TABLE IF EXISTS role_permissions')
    op.execute('DROP TABLE IF EXISTS auth_roles')
    op.execute('DROP TABLE IF EXISTS permissions')
    op.execute('DROP TABLE IF EXISTS waitlists')
    op.execute('DROP TABLE IF EXISTS Media')
    op.execute('DROP TABLE IF EXISTS roster_roles')
    op.execute('DROP TABLE IF EXISTS Session_Logs')
    op.execute('DROP TABLE IF EXISTS votes')
    op.execute('DROP TABLE IF EXISTS roster')
    op.execute('DROP TABLE IF EXISTS pathway_projects')
    op.execute('DROP TABLE IF EXISTS achievements')
    op.execute('DROP TABLE IF EXISTS Users')
    op.execute('DROP TABLE IF EXISTS Session_Types')
    op.execute('DROP TABLE IF EXISTS Meetings')
    op.execute('DROP TABLE IF EXISTS roles')
    op.execute('DROP TABLE IF EXISTS pathways')
    op.execute('DROP TABLE IF EXISTS level_roles')
    op.execute('DROP TABLE IF EXISTS Projects')
    op.execute('DROP TABLE IF EXISTS Contacts')
    
    # Re-enable foreign key checks
    op.execute('SET FOREIGN_KEY_CHECKS=1')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop all existing tables first
    _drop_all_tables()
    
    op.create_table('Contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Type', sa.String(length=50), nullable=False),
    sa.Column('Club', sa.String(length=100), nullable=True),
    sa.Column('Date_Created', sa.Date(), nullable=True),
    sa.Column('Completed_Paths', sa.String(length=255), nullable=True),
    sa.Column('DTM', sa.Boolean(), nullable=True),
    sa.Column('Phone_Number', sa.String(length=50), nullable=True),
    sa.Column('Bio', sa.Text(), nullable=True),
    sa.Column('Member_ID', sa.String(length=50), nullable=True),
    sa.Column('Mentor_ID', sa.Integer(), nullable=True),
    sa.Column('Current_Path', sa.String(length=50), nullable=True),
    sa.Column('Next_Project', sa.String(length=100), nullable=True),
    sa.Column('credentials', sa.String(length=10), nullable=True),
    sa.Column('Avatar_URL', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['Mentor_ID'], ['Contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Member_ID'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Project_Name', sa.String(length=255), nullable=False),
    sa.Column('Format', sa.String(length=50), nullable=True),
    sa.Column('Duration_Min', sa.Integer(), nullable=True),
    sa.Column('Duration_Max', sa.Integer(), nullable=True),
    sa.Column('Introduction', sa.String(length=1000), nullable=True),
    sa.Column('Overview', sa.String(length=1000), nullable=True),
    sa.Column('Purpose', sa.String(length=255), nullable=True),
    sa.Column('Requirements', sa.String(length=500), nullable=True),
    sa.Column('Resources', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('count_required', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pathways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('abbr', sa.String(length=5), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'obsolete', name='pathway_status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('award_category', sa.String(length=30), nullable=True),
    sa.Column('needs_approval', sa.Boolean(), nullable=False),
    sa.Column('is_distinct', sa.Boolean(), nullable=False),
    sa.Column('is_member_only', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('Meeting_Number', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('Meeting_Date', sa.Date(), nullable=True),
    sa.Column('Meeting_Title', sa.String(length=255), nullable=True),
    sa.Column('Subtitle', sa.String(length=255), nullable=True),
    sa.Column('Start_Time', sa.Time(), nullable=True),
    sa.Column('Meeting_Template', sa.String(length=100), nullable=True),
    sa.Column('WOD', sa.String(length=100), nullable=True),
    sa.Column('best_table_topic_id', sa.Integer(), nullable=True),
    sa.Column('best_evaluator_id', sa.Integer(), nullable=True),
    sa.Column('best_speaker_id', sa.Integer(), nullable=True),
    sa.Column('best_role_taker_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('ge_mode', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('unpublished', 'not started', 'running', 'finished', 'cancelled', name='meeting_status'), nullable=False),
    sa.Column('nps', sa.Float(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['best_evaluator_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['best_role_taker_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['best_speaker_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['best_table_topic_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['Media.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Meeting_Number')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('resource', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_permissions_category'), ['category'], unique=False)

    op.create_table('auth_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('auth_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_roles_name'), ['name'], unique=True)

    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='unique_role_permission')
    )

    op.create_table('Session_Types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=255), nullable=False),
    sa.Column('Default_Owner', sa.String(length=255), nullable=True),
    sa.Column('Is_Section', sa.Boolean(), nullable=True),
    sa.Column('Is_Hidden', sa.Boolean(), nullable=True),
    sa.Column('Predefined', sa.Boolean(), nullable=True),
    sa.Column('Valid_for_Project', sa.Boolean(), nullable=True),
    sa.Column('Duration_Min', sa.Integer(), nullable=True),
    sa.Column('Duration_Max', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Title')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('Contact_ID', sa.Integer(), nullable=True),
    sa.Column('Pass_Hash', sa.String(length=255), nullable=False),
    sa.Column('Date_Created', sa.Date(), nullable=True),
    sa.Column('Role', sa.String(length=50), nullable=False),
    sa.Column('Status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['Contact_ID'], ['Contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Contact_ID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Username')
    )

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['Users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='unique_user_role')
    )
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('achievement_type', sa.Enum('level-completion', 'path-completion', 'program-completion', name='achievement_type_enum'), nullable=False),
    sa.Column('path_name', sa.String(length=100), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pathway_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('elective', 'required', 'other', name='pathway_project_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['pathways.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_number', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('ticket', sa.String(length=20), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('contact_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_number', sa.Integer(), nullable=False),
    sa.Column('voter_identifier', sa.String(length=64), nullable=False),
    sa.Column('award_category', sa.Enum('speaker', 'evaluator', 'role-taker', 'table-topic', name='award_category_enum'), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index('idx_meeting_voter', ['meeting_number', 'voter_identifier'], unique=False)

    op.create_table('Session_Logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Meeting_Number', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('Meeting_Seq', sa.Integer(), nullable=True),
    sa.Column('Session_Title', sa.String(length=255), nullable=True),
    sa.Column('Type_ID', sa.Integer(), nullable=False),
    sa.Column('Owner_ID', sa.Integer(), nullable=True),
    sa.Column('credentials', sa.String(length=255), nullable=True),
    sa.Column('Project_ID', sa.Integer(), nullable=True),
    sa.Column('Start_Time', sa.Time(), nullable=True),
    sa.Column('Duration_Min', sa.Integer(), nullable=True),
    sa.Column('Duration_Max', sa.Integer(), nullable=True),
    sa.Column('Notes', sa.String(length=1000), nullable=True),
    sa.Column('Status', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('project_code', sa.String(length=10), nullable=True),
    sa.Column('pathway', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['Meeting_Number'], ['Meetings.Meeting_Number'], ),
    sa.ForeignKeyConstraint(['Owner_ID'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['Project_ID'], ['Projects.id'], ),
    sa.ForeignKeyConstraint(['Type_ID'], ['Session_Types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roster_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['roster.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roster_id', 'role_id', name='uq_roster_role')
    )
    op.create_table('Media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['Session_Logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waitlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_log_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['session_log_id'], ['Session_Logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Seed metadata
    import os
    import json
    
    file_path = os.path.join(os.path.dirname(__file__), '../../deploy/metadata_dump.json')
    if os.path.exists(file_path):
        with open(file_path, 'r') as f:
            data = json.load(f)
            
        # Seed roles
        roles_table = sa.table('roles',
            sa.column('id', sa.Integer),
            sa.column('name', sa.String),
            sa.column('icon', sa.String),
            sa.column('type', sa.String),
            sa.column('award_category', sa.String),
            sa.column('needs_approval', sa.Boolean),
            sa.column('is_distinct', sa.Boolean),
            sa.column('is_member_only', sa.Boolean)
        )
        op.bulk_insert(roles_table, data.get('roles', []))
        
        # Seed pathways
        pathways_table = sa.table('pathways',
            sa.column('id', sa.Integer),
            sa.column('name', sa.String),
            sa.column('abbr', sa.String),
            sa.column('type', sa.String),
            sa.column('status', sa.String)
        )
        op.bulk_insert(pathways_table, data.get('pathways', []))
        
        # Seed projects
        projects_table = sa.table('Projects',
            sa.column('id', sa.Integer),
            sa.column('Project_Name', sa.String),
            sa.column('Format', sa.String),
            sa.column('Duration_Min', sa.Integer),
            sa.column('Duration_Max', sa.Integer),
            sa.column('Introduction', sa.String),
            sa.column('Overview', sa.String),
            sa.column('Purpose', sa.String),
            sa.column('Requirements', sa.String),
            sa.column('Resources', sa.String)
        )
        op.bulk_insert(projects_table, data.get('projects', []))
        
        # Seed level_roles
        level_roles_table = sa.table('level_roles',
            sa.column('id', sa.Integer),
            sa.column('level', sa.Integer),
            sa.column('role', sa.String),
            sa.column('type', sa.String),
            sa.column('count_required', sa.Integer)
        )
        op.bulk_insert(level_roles_table, data.get('level_roles', []))
        
        # Seed Session_Types
        session_types_table = sa.table('Session_Types',
            sa.column('id', sa.Integer),
            sa.column('Title', sa.String),
            sa.column('Default_Owner', sa.String),
            sa.column('Is_Section', sa.Boolean),
            sa.column('Is_Hidden', sa.Boolean),
            sa.column('Predefined', sa.Boolean),
            sa.column('Valid_for_Project', sa.Boolean),
            sa.column('Duration_Min', sa.Integer),
            sa.column('Duration_Max', sa.Integer),
            sa.column('role_id', sa.Integer)
        )
        op.bulk_insert(session_types_table, data.get('session_types', []))
        
        # Seed pathway_projects
        pathway_projects_table = sa.table('pathway_projects',
            sa.column('id', sa.Integer),
            sa.column('path_id', sa.Integer),
            sa.column('project_id', sa.Integer),
            sa.column('code', sa.String),
            sa.column('level', sa.Integer),
            sa.column('type', sa.String)
        )
        op.bulk_insert(pathway_projects_table, data.get('pathway_projects', []))

        # Seed permissions
        permissions_table = sa.table('permissions',
            sa.column('id', sa.Integer),
            sa.column('name', sa.String),
            sa.column('description', sa.Text),
            sa.column('category', sa.String),
            sa.column('resource', sa.String),
            sa.column('action', sa.String),
            sa.column('created_at', sa.DateTime)
        )
        op.bulk_insert(permissions_table, data.get('permissions', []))

        # Seed auth_roles
        auth_roles_table = sa.table('auth_roles',
            sa.column('id', sa.Integer),
            sa.column('name', sa.String),
            sa.column('description', sa.Text),
            sa.column('level', sa.Integer),
            sa.column('created_at', sa.DateTime)
        )
        op.bulk_insert(auth_roles_table, data.get('auth_roles', []))

        # Seed role_permissions
        role_permissions_table = sa.table('role_permissions',
            sa.column('id', sa.Integer),
            sa.column('role_id', sa.Integer),
            sa.column('permission_id', sa.Integer)
        )
        op.bulk_insert(role_permissions_table, data.get('role_permissions', []))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_all_tables()
    # ### end Alembic commands ###
