"""add excomm_id to meetings

Revision ID: 18df9d8168f7
Revises: f0ab859c9cc1
Create Date: 2026-02-02 14:59:06.697493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18df9d8168f7'
down_revision = 'f0ab859c9cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excomm_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Meetings_excomm_id'), ['excomm_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_Meetings_excomm_id_excomm'), 'excomm', ['excomm_id'], ['id'])

    # Backfill excomm_id for existing meetings
    op.execute("""
        UPDATE Meetings m
        JOIN excomm e ON m.club_id = e.club_id
        SET m.excomm_id = e.id
        WHERE m.Meeting_Date >= e.start_date AND m.Meeting_Date <= e.end_date
        AND m.excomm_id IS NULL
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Meetings_excomm_id_excomm'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Meetings_excomm_id'))
        batch_op.drop_column('excomm_id')

    # ### end Alembic commands ###
