"""Rename Projects.ID to id

Revision ID: 1da845e56e6a
Revises: 3af406c02207
Create Date: 2025-12-29 20:57:48.923387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1da845e56e6a'
down_revision = '3af406c02207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop Foreign Keys referencing the column to be renamed IF THEY EXIST
    
    # helper to check existing constraints
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # Check Session_Logs
    session_logs_fks = [fk['name'] for fk in inspector.get_foreign_keys('Session_Logs')]
    if 'fk_project' in session_logs_fks:
        with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
            batch_op.drop_constraint('fk_project', type_='foreignkey')

    # Check pathway_projects
    pathway_projects_fks = [fk['name'] for fk in inspector.get_foreign_keys('pathway_projects')]
    if 'pathway_projects_ibfk_2' in pathway_projects_fks:
        with op.batch_alter_table('pathway_projects', schema=None) as batch_op:
            batch_op.drop_constraint('pathway_projects_ibfk_2', type_='foreignkey')

    # 2. Rename the column
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.alter_column('ID', new_column_name='id', existing_type=sa.Integer(), nullable=False)

    # 3. Recreate Foreign Keys pointing to the new column name
    # We must ensure we don't create duplicate keys if the drop above failed or if they were already pointing to the correct column (unlikely in this migration flow)
    # But since we conditionally dropped if they existed, we can assume we need to create them now (or recreate them correctly).
    # Note: If the drop block above ran, they are gone. If it didn't run, they didn't exist. So we are safe to create.
    
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
         batch_op.create_foreign_key(batch_op.f('fk_project'), 'Projects', ['Project_ID'], ['id'])

    with op.batch_alter_table('pathway_projects', schema=None) as batch_op:
         batch_op.create_foreign_key(batch_op.f('pathway_projects_ibfk_2'), 'Projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop FKs
    with op.batch_alter_table('pathway_projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pathway_projects_ibfk_2'), type_='foreignkey')

    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_project'), type_='foreignkey')

    # 2. Rename back
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.alter_column('id', new_column_name='ID', existing_type=sa.Integer(), nullable=False)

    # 3. Recreate FKs
    # (Skipped: Original state had no FKs)
    # with op.batch_alter_table('pathway_projects', schema=None) as batch_op:
    #     batch_op.create_foreign_key('pathway_projects_ibfk_2', 'Projects', ['project_id'], ['ID'])

    # with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
    #     batch_op.create_foreign_key('fk_project', 'Projects', ['Project_ID'], ['ID'])

    # ### end Alembic commands ###
