"""add a type field to Meeting

Revision ID: 28c215bc6e93
Revises: 59920495c8f1
Create Date: 2025-11-10 22:05:02.219614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c215bc6e93'
down_revision = '59920495c8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
