"""rename contact home_club to display_club_name

Revision ID: 2930134a6e92
Revises: 8d7c22139146
Create Date: 2026-06-11 15:24:19.537890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2930134a6e92'
down_revision = '8d7c22139146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('Contacts')]

    if 'home_club' in columns:
        with op.batch_alter_table('Contacts', schema=None) as batch_op:
            batch_op.alter_column('home_club', new_column_name='display_club_name', type_=sa.String(length=200), existing_nullable=True)
    elif 'display_club_name' not in columns:
        with op.batch_alter_table('Contacts', schema=None) as batch_op:
            batch_op.add_column(sa.Column('display_club_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('Contacts')]

    if 'display_club_name' in columns:
        with op.batch_alter_table('Contacts', schema=None) as batch_op:
            batch_op.alter_column('display_club_name', new_column_name='home_club', type_=sa.String(length=200), existing_nullable=True)
    elif 'home_club' not in columns:
        with op.batch_alter_table('Contacts', schema=None) as batch_op:
            batch_op.add_column(sa.Column('home_club', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###
