"""Add club_id to Meetings table for multi-club support

Revision ID: 2bf0e03b7ec5
Revises: 74f4cf30ecc0
Create Date: 2026-01-16 10:13:17.391623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf0e03b7ec5'
down_revision = '74f4cf30ecc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Get connection to check what exists
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    # 1. Create contact_clubs junction table (drop if already exists from failed run)
    if 'contact_clubs' in existing_tables:
        op.drop_table('contact_clubs')
        
    op.create_table('contact_clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('membership_type', sa.String(length=50), nullable=True),
    sa.Column('joined_date', sa.Date(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'club_id', name='uq_contact_club')
    )
    with op.batch_alter_table('contact_clubs', schema=None) as batch_op:
        batch_op.create_index('ix_contact_clubs_club', ['club_id'], unique=False)
        batch_op.create_index('ix_contact_clubs_contact', ['contact_id'], unique=False)

    # 2. Add club_id to Meetings as NULLABLE first
    meetings_columns = [col['name'] for col in inspector.get_columns('Meetings')]
    meetings_indexes = [idx['name'] for idx in inspector.get_indexes('Meetings')]
    
    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        if 'club_id' not in meetings_columns:
            batch_op.add_column(sa.Column('club_id', sa.Integer(), nullable=True))
        
        if 'ix_Meetings_club_id' not in meetings_indexes:
            batch_op.create_index(batch_op.f('ix_Meetings_club_id'), ['club_id'], unique=False)

    # 3. Create default club from settings.ini if not exists
    from configparser import ConfigParser
    import os
    
    config = ConfigParser()
    settings_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'settings.ini')
    
    if True: # Always attempt to ensure a club exists
        if os.path.exists(settings_path):
            config.read(settings_path)
        
        # Check if default club already exists
        connection = op.get_bind()
        result = connection.execute(sa.text("SELECT id FROM clubs LIMIT 1"))
        existing_club = result.fetchone()
        
        if not existing_club:
            # Insert default club
            club_no = config.get('club', 'club_no', fallback='000000')
            club_name = config.get('club', 'club_name', fallback='Default Club')
            district = config.get('club', 'district', fallback='')
            division = config.get('club', 'division', fallback='')
            area = config.get('club', 'area', fallback='')
            club_address = config.get('club', 'club_address', fallback='')
            meeting_date = config.get('club', 'meeting_date', fallback='')
            meeting_time = config.get('club', 'meeting_time', fallback='19:00:00')
            contact_phone = config.get('club', 'contact_phone_number', fallback='')
            
            # Note: website column was added in 74f4cf30ecc0 (previous migration)
            # so we can insert it if we want, but it's nullable.
            
            connection.execute(sa.text("""
                INSERT INTO clubs (club_no, club_name, district, division, area, 
                                  club_address, meeting_date, meeting_time, contact_phone_number,
                                  created_at, updated_at)
                VALUES (:club_no, :club_name, :district, :division, :area,
                        :club_address, :meeting_date, :meeting_time, :contact_phone,
                        NOW(), NOW())
            """), {
                'club_no': club_no,
                'club_name': club_name,
                'district': district,
                'division': division,
                'area': area,
                'club_address': club_address,
                'meeting_date': meeting_date,
                'meeting_time': meeting_time,
                'contact_phone': contact_phone
            })
    
    # 4. Populate existing meetings with default club
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE Meetings 
        SET club_id = (SELECT id FROM clubs ORDER BY id LIMIT 1)
        WHERE club_id IS NULL
    """))
    
    # 5. Populate contact_clubs with existing contacts
    connection.execute(sa.text("""
        INSERT INTO contact_clubs (contact_id, club_id, membership_type, is_primary, joined_date, created_at, updated_at)
        SELECT c.id, 
               (SELECT id FROM clubs ORDER BY id LIMIT 1),
               c.Type,
               1,
               c.Date_Created,
               NOW(),
               NOW()
        FROM Contacts c
        WHERE NOT EXISTS (
            SELECT 1 FROM contact_clubs cc WHERE cc.contact_id = c.id
        )
    """))
    
    # 6. Add foreign key constraint and make club_id non-nullable
    meetings_fks = [fk['name'] for fk in inspector.get_foreign_keys('Meetings')]
    
    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        if 'fk_meetings_club' not in meetings_fks:
            batch_op.create_foreign_key('fk_meetings_club', 'clubs', ['club_id'], ['id'])
        
        # Check if nullable is already False
        col_info = next((c for c in inspector.get_columns('Meetings') if c['name'] == 'club_id'), None)
        if col_info and col_info.get('nullable', True):
            batch_op.alter_column('club_id', nullable=False, existing_type=sa.Integer())

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Get connection to check what exists
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    
    # 1. Drop foreign key and club_id column from Meetings (if they exist)
    meetings_fks = [fk['name'] for fk in inspector.get_foreign_keys('Meetings')]
    meetings_indexes = [idx['name'] for idx in inspector.get_indexes('Meetings')]
    meetings_columns = [col['name'] for col in inspector.get_columns('Meetings')]
    
    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        # Drop foreign key if it exists
        if 'fk_meetings_club' in meetings_fks:
            batch_op.drop_constraint('fk_meetings_club', type_='foreignkey')
        
        # Drop index if it exists
        if 'ix_Meetings_club_id' in meetings_indexes:
            batch_op.drop_index(batch_op.f('ix_Meetings_club_id'))
        
        # Drop column if it exists
        if 'club_id' in meetings_columns:
            batch_op.drop_column('club_id')

    # 2. Drop contact_clubs table if it exists
    existing_tables = inspector.get_table_names()
    if 'contact_clubs' in existing_tables:
        op.drop_table('contact_clubs')
    # ### end Alembic commands ###
