"""Initial consolidation

Revision ID: 2ce4ec3ec79c
Revises: 
Create Date: 2026-01-13 12:47:15.545836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ce4ec3ec79c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_column('comments')
        batch_op.drop_column('score')
        batch_op.drop_column('question')

    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
