"""add Current_Path and Next_Project to User table

Revision ID: 2e3b4952b50f
Revises: 8de2f381cd37
Create Date: 2025-11-16 21:26:49.576080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3b4952b50f'
down_revision = '8de2f381cd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('Current_Path', sa.String(length=50), nullable=True))
        batch_op.add_column(
            sa.Column('Next_Project', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###

    # ### custom data migration for MySQL ###
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE Users
        JOIN Contacts ON Users.Contact_ID = Contacts.id
        SET Users.Current_Path = Contacts.Working_Path,
            Users.Next_Project = Contacts.Next_Project
        WHERE Users.Contact_ID IS NOT NULL
    """))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('Next_Project')
        batch_op.drop_column('Current_Path')

    # ### end Alembic commands ###
