"""Make order_number nullable

Revision ID: 2f42e35cc515
Revises: f6c80eb1b7bb
Create Date: 2026-01-13 00:24:50.058706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f42e35cc515'
down_revision = 'f6c80eb1b7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
