"""Add Vote model

Revision ID: 33229ae767dc
Revises: d44b399886f5
Create Date: 2025-11-25 00:39:19.308035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33229ae767dc'
down_revision = 'd44b399886f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_number', sa.Integer(), nullable=False),
    sa.Column('voter_identifier', sa.String(length=64), nullable=False),
    sa.Column('award_category', sa.Enum('speaker', 'evaluator', 'role-taker', 'table-topic', name='award_category_enum'), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index('idx_meeting_voter', ['meeting_number', 'voter_identifier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index('idx_meeting_voter')

    op.drop_table('votes')
    # ### end Alembic commands ###
