"""add a type field to the tickets table

Revision ID: 367907ecdf72
Revises: 4390b0c7464c
Create Date: 2026-03-06 11:29:59.021778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '367907ecdf72'
down_revision = '4390b0c7464c'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_tickets_name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_tickets_name'), ['name'], unique=True)

    # ### end Alembic commands ###
