"""add manager_id to meetings

Revision ID: 3af406c02207
Revises: f0617785810c
Create Date: 2025-12-29 18:58:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af406c02207'
down_revision = '8e034df1676e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Meetings', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Meetings', 'Contacts', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Meetings', type_='foreignkey')
    op.drop_column('Meetings', 'manager_id')
    # ### end Alembic commands ###
