"""Add expired_at to tickets

Revision ID: 3bc5170607b7
Revises: b76d8ef01dd1
Create Date: 2026-03-12 01:25:57.382776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bc5170607b7'
down_revision = 'b76d8ef01dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired_at', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('expired_at')

    # ### end Alembic commands ###
