"""add featured column to session types

Revision ID: 3d5e8695df3c
Revises: 4335594d965c
Create Date: 2026-06-06 00:12:01.268933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5e8695df3c'
down_revision = '4335594d965c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('Session_Types')]
    if 'Featured' not in columns:
        with op.batch_alter_table('Session_Types', schema=None) as batch_op:
            batch_op.add_column(sa.Column('Featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Types', schema=None) as batch_op:
        batch_op.drop_column('Featured')
    # ### end Alembic commands ###
