"""add_section_id_to_session_logs

Revision ID: 4335594d965c
Revises: a1b2c3d4e5f7
Create Date: 2026-06-05 22:45:54.750815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4335594d965c'
down_revision = 'a1b2c3d4e5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_Session_Logs_section_id_Session_Logs'), 'Session_Logs', ['section_id'], ['id'], ondelete='SET NULL')

    # Populate existing data:
    session_logs = sa.Table(
        'Session_Logs',
        sa.MetaData(),
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('meeting_id', sa.Integer()),
        sa.Column('Meeting_Seq', sa.Integer()),
        sa.Column('Type_ID', sa.Integer()),
        sa.Column('section_id', sa.Integer())
    )
    session_types = sa.Table(
        'Session_Types',
        sa.MetaData(),
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('Is_Section', sa.Boolean())
    )

    connection = op.get_bind()

    # Query all session logs with their type's Is_Section flag
    query = sa.select(
        session_logs.c.id,
        session_logs.c.meeting_id,
        session_logs.c.Meeting_Seq,
        session_types.c.Is_Section
    ).select_from(
        session_logs.join(session_types, session_logs.c.Type_ID == session_types.c.id)
    ).order_by(
        session_logs.c.meeting_id,
        session_logs.c.Meeting_Seq.asc()
    )

    results = connection.execute(query).fetchall()

    # Group results by meeting_id and recalculate section_id
    from collections import defaultdict
    meetings = defaultdict(list)
    for row in results:
        meetings[row[1]].append({
            'id': row[0],
            'is_section': bool(row[3])
        })

    for meeting_id, logs in meetings.items():
        current_section_id = None
        for log in logs:
            if log['is_section']:
                current_section_id = log['id']
                connection.execute(
                    session_logs.update().where(session_logs.c.id == log['id']).values(section_id=log['id'])
                )
            else:
                connection.execute(
                    session_logs.update().where(session_logs.c.id == log['id']).values(section_id=current_section_id)
                )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Session_Logs_section_id_Session_Logs'), type_='foreignkey')
        batch_op.drop_column('section_id')

    # ### end Alembic commands ###
