"""add SessionLog.state str field

Revision ID: 46edc2b87fa0
Revises: 28c215bc6e93
Create Date: 2025-11-11 23:17:43.342338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46edc2b87fa0'
down_revision = '28c215bc6e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
