"""Add Pathway and PathwayProject models

Revision ID: 4c34ee4b927d
Revises: ed431c6389e2
Create Date: 2025-12-03 15:52:52.394415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c34ee4b927d'
down_revision = 'ed431c6389e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pathways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('abbr', sa.String(length=5), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pathway_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['pathways.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pathway_projects')
    op.drop_table('pathways')
    # ### end Alembic commands ###
