"""drop membership_type joined_date is_primary from contact_clubs

Revision ID: 4ff8f0ad4ddb
Revises: cd0cd55d7e4e
Create Date: 2026-01-18 15:44:01.077814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ff8f0ad4ddb'
down_revision = 'cd0cd55d7e4e'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('contact_clubs', schema=None) as batch_op:
        batch_op.drop_column('membership_type')
        batch_op.drop_column('is_primary')
        batch_op.drop_column('joined_date')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('is_primary', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('membership_type', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
