"""add awards table and link meeting configs

Revision ID: 502a72bf7bc4
Revises: 73cd73774ebe
Create Date: 2026-06-16 16:57:29.317672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502a72bf7bc4'
down_revision = '73cd73774ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('max_votes_per_user', sa.Integer(), nullable=False),
    sa.Column('max_winners', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_awards_club_id_clubs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_awards')),
    sa.UniqueConstraint('club_id', 'category', name='uq_club_award_category')
    )
    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_awards_club_id'), ['club_id'], unique=False)

    op.create_table('award_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Integer(), nullable=False),
    sa.Column('meeting_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], name=op.f('fk_award_roles_award_id_awards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_role_id'], ['meeting_roles.id'], name=op.f('fk_award_roles_meeting_role_id_meeting_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_award_roles')),
    sa.UniqueConstraint('award_id', 'meeting_role_id', name='uq_award_role')
    )
    with op.batch_alter_table('award_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_award_roles_award_id'), ['award_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_award_roles_meeting_role_id'), ['meeting_role_id'], unique=False)

    with op.batch_alter_table('meeting_award_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('award_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_meeting_award_configs_award_id'), ['award_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_meeting_award_configs_award_id_awards'), 'awards', ['award_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('meeting_award_winners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('award_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_meeting_award_winners_award_id'), ['award_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_meeting_award_winners_award_id_awards'), 'awards', ['award_id'], ['id'], ondelete='SET NULL')

    # Data Migration Logic
    bind = op.get_bind()
    
    # Get all clubs
    clubs = bind.execute(sa.text("SELECT id FROM clubs")).fetchall()
    
    for club in clubs:
        club_id = club[0]
        
        # We will create the 4 standard awards for this club
        standard_defaults = [
            ("Best Speaker", "speaker"),
            ("Best Evaluator", "evaluator"),
            ("Best Table Topic", "table-topic"),
            ("Best Role Taker", "role-taker")
        ]
        
        award_ids = []
        for name, category in standard_defaults:
            # Check if already exists (should not, but safety first)
            existing = bind.execute(
                sa.text("SELECT id FROM awards WHERE club_id = :club_id AND category = :category"),
                {"club_id": club_id, "category": category}
            ).fetchone()
            
            if existing:
                award_id = existing[0]
            else:
                # Insert the award
                bind.execute(
                    sa.text("INSERT INTO awards (club_id, name, category, max_votes_per_user, max_winners) "
                            "VALUES (:club_id, :name, :category, 1, 1)"),
                    {"club_id": club_id, "name": name, "category": category}
                )
                # Get the inserted award ID
                award_id = bind.execute(
                    sa.text("SELECT id FROM awards WHERE club_id = :club_id AND category = :category"),
                    {"club_id": club_id, "category": category}
                ).fetchone()[0]
                
            award_ids.append(award_id)
            
            # Now let's find existing role associations for this category in this club's meetings
            existing_role_ids = bind.execute(
                sa.text(
                    "SELECT DISTINCT arc.meeting_role_id "
                    "FROM award_role_configs arc "
                    "JOIN meeting_award_configs mac ON arc.award_config_id = mac.id "
                    "JOIN Meetings m ON mac.meeting_id = m.id "
                    "WHERE m.club_id = :club_id AND mac.award_category = :category"
                ),
                {"club_id": club_id, "category": category}
            ).fetchall()
            
            for row in existing_role_ids:
                role_id = row[0]
                # Insert association if not exists
                assoc_exists = bind.execute(
                    sa.text("SELECT id FROM award_roles WHERE award_id = :award_id AND meeting_role_id = :role_id"),
                    {"award_id": award_id, "role_id": role_id}
                ).fetchone()
                if not assoc_exists:
                    bind.execute(
                        sa.text("INSERT INTO award_roles (award_id, meeting_role_id) VALUES (:award_id, :role_id)"),
                        {"award_id": award_id, "role_id": role_id}
                    )
                    
        # Update Club.default_awards with JSON array of award IDs
        import json
        default_awards_json = json.dumps(award_ids)
        bind.execute(
            sa.text("UPDATE clubs SET default_awards = :default_awards WHERE id = :club_id"),
            {"default_awards": default_awards_json, "club_id": club_id}
        )

    # G. Migrate existing MeetingAwardConfig rows to link to correct award_id
    configs = bind.execute(
        sa.text("SELECT mac.id, m.club_id, mac.award_category FROM meeting_award_configs mac "
                "JOIN Meetings m ON mac.meeting_id = m.id")
    ).fetchall()
    
    for config_id, club_id, category in configs:
        # Check if an award for this club and category exists
        award = bind.execute(
            sa.text("SELECT id FROM awards WHERE club_id = :club_id AND category = :category"),
            {"club_id": club_id, "category": category}
        ).fetchone()
        
        if not award:
            # Create a custom award in this club for this category
            name = category.replace('-', ' ').replace('_', ' ').title()
            bind.execute(
                sa.text("INSERT INTO awards (club_id, name, category, max_votes_per_user, max_winners) "
                        "VALUES (:club_id, :name, :category, 1, 1)"),
                {"club_id": club_id, "name": name, "category": category}
            )
            award = bind.execute(
                sa.text("SELECT id FROM awards WHERE club_id = :club_id AND category = :category"),
                {"club_id": club_id, "category": category}
            ).fetchone()
            
        award_id = award[0]
        # Update config
        bind.execute(
            sa.text("UPDATE meeting_award_configs SET award_id = :award_id WHERE id = :config_id"),
            {"award_id": award_id, "config_id": config_id}
        )

    # H. Migrate existing MeetingAwardWinner rows to link to correct award_id
    winners = bind.execute(
        sa.text("SELECT maw.id, m.club_id, maw.award_category FROM meeting_award_winners maw "
                "JOIN Meetings m ON maw.meeting_id = m.id")
    ).fetchall()
    
    for winner_id, club_id, category in winners:
        # Check if an award for this club and category exists
        award = bind.execute(
            sa.text("SELECT id FROM awards WHERE club_id = :club_id AND category = :category"),
            {"club_id": club_id, "category": category}
        ).fetchone()
        
        if award:
            award_id = award[0]
            # Update winner
            bind.execute(
                sa.text("UPDATE meeting_award_winners SET award_id = :award_id WHERE id = :winner_id"),
                {"award_id": award_id, "winner_id": winner_id}
            )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_award_winners', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_meeting_award_winners_award_id_awards'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_meeting_award_winners_award_id'))
        batch_op.drop_column('award_id')

    with op.batch_alter_table('meeting_award_configs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_meeting_award_configs_award_id_awards'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_meeting_award_configs_award_id'))
        batch_op.drop_column('award_id')

    with op.batch_alter_table('award_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_award_roles_meeting_role_id'))
        batch_op.drop_index(batch_op.f('ix_award_roles_award_id'))

    op.drop_table('award_roles')
    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_awards_club_id'))

    op.drop_table('awards')
    # ### end Alembic commands ###
