"""change votes award_category to String

Revision ID: 519065b594b4
Revises: 14b1f51a5a3f
Create Date: 2026-06-15 00:21:42.514727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '519065b594b4'
down_revision = '14b1f51a5a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('award_category',
               existing_type=mysql.ENUM('speaker', 'evaluator', 'role-taker', 'table-topic', 'debater'),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('award_category',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('speaker', 'evaluator', 'role-taker', 'table-topic', 'debater'),
               existing_nullable=True)

    # ### end Alembic commands ###
