"""add club_id to session_types and meeting_roles

Revision ID: 58e5efb96174
Revises: a7d46f73c689
Create Date: 2026-01-27 18:06:52.605491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e5efb96174'
down_revision = 'a7d46f73c689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.Integer(), nullable=True))
        # batch_op.drop_index(batch_op.f('uq_Session_Types_Title'))
        batch_op.create_index(batch_op.f('ix_Session_Types_club_id'), ['club_id'], unique=False)
        batch_op.create_unique_constraint('uq_session_type_title_club', ['Title', 'club_id'])
        batch_op.create_foreign_key(batch_op.f('fk_Session_Types_club_id_clubs'), 'clubs', ['club_id'], ['id'])

    with op.batch_alter_table('meeting_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_meeting_roles_club_id'), ['club_id'], unique=False)
        batch_op.create_unique_constraint('uq_meeting_role_name_club', ['name', 'club_id'])
        batch_op.create_foreign_key(batch_op.f('fk_meeting_roles_club_id_clubs'), 'clubs', ['club_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_meeting_roles_club_id_clubs'), type_='foreignkey')
        batch_op.drop_constraint('uq_meeting_role_name_club', type_='unique')
        batch_op.drop_index(batch_op.f('ix_meeting_roles_club_id'))
        batch_op.drop_column('club_id')

    with op.batch_alter_table('Session_Types', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Session_Types_club_id_clubs'), type_='foreignkey')
        batch_op.drop_constraint('uq_session_type_title_club', type_='unique')
        batch_op.drop_index(batch_op.f('ix_Session_Types_club_id'))
        batch_op.create_index(batch_op.f('uq_Session_Types_Title'), ['Title'], unique=True)
        batch_op.drop_column('club_id')

    # ### end Alembic commands ###
