"""update Meetings table

Revision ID: 59920495c8f1
Revises: 
Create Date: 2025-11-08 23:37:39.888903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59920495c8f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        pass # batch_op.drop_index(batch_op.f('idx_meeting_number'))

    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.alter_column('Project_Name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.alter_column('Meeting_Number',
               existing_type=mysql.SMALLINT(unsigned=True),
               nullable=False)
        batch_op.alter_column('Type_ID',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['Email'])
        batch_op.create_foreign_key(None, 'Contacts', ['Contact_ID'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.alter_column('Type_ID',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('Meeting_Number',
               existing_type=mysql.SMALLINT(unsigned=True),
               nullable=True)

    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.alter_column('Project_Name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_meeting_number'), ['Meeting_Number'], unique=False)

    # ### end Alembic commands ###
