"""Add pathway field to SessionLog

Revision ID: 59e4cd3ff135
Revises: a4780e9744df
Create Date: 2025-12-30 19:03:01.750045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e4cd3ff135'
down_revision = 'a4780e9744df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pathway', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.drop_column('pathway')

    # ### end Alembic commands ###
