"""drop Code_xx columns from Project

Revision ID: 5a6502921e8a
Revises: 9c6737b06886
Create Date: 2025-12-03 17:41:21.258796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a6502921e8a'
down_revision = '9c6737b06886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.drop_column('Code_MS')
        batch_op.drop_column('Code_PI')
        batch_op.drop_column('Code_DTM')
        batch_op.drop_column('Code_PM')
        batch_op.drop_column('Code_EH')
        batch_op.drop_column('Code_DL')
        batch_op.drop_column('Code_VC')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Code_VC', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('Code_DL', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('Code_EH', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('Code_PM', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('Code_DTM', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('Code_PI', mysql.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('Code_MS', mysql.VARCHAR(length=5), nullable=True))

    # ### end Alembic commands ###
