"""add_club_status_and_user_favorites

Revision ID: 5c3141ca3418
Revises: b0ea9108e051
Create Date: 2026-06-04 23:11:07.818832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3141ca3418'
down_revision = 'b0ea9108e051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_clubs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_user_favorite_clubs_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_favorite_clubs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'club_id', name=op.f('pk_user_favorite_clubs'))
    )
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='active'))

    # Set Technical Support to super
    op.execute("UPDATE clubs SET status = 'super' WHERE club_name = 'Technical Support' OR club_name = 'Tech Support'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('user_favorite_clubs')
    # ### end Alembic commands ###
