"""Add planner table

Revision ID: 603a9a419abf
Revises: 18df9d8168f7
Create Date: 2026-02-07 12:56:55.585602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603a9a419abf'
down_revision = '18df9d8168f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_number', sa.Integer(), nullable=True),
    sa.Column('meeting_role_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_planner_club_id_clubs')),
    sa.ForeignKeyConstraint(['meeting_role_id'], ['meeting_roles.id'], name=op.f('fk_planner_meeting_role_id_meeting_roles')),
    sa.ForeignKeyConstraint(['project_id'], ['Projects.id'], name=op.f('fk_planner_project_id_Projects')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_planner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planner'))
    )
    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planner_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planner_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planner_user_id'))
        batch_op.drop_index(batch_op.f('ix_planner_club_id'))

    op.drop_table('planner')
    # ### end Alembic commands ###
