"""add band column to level_roles

Revision ID: 65bc969cc9a2
Revises: 09e97b1b57ba
Create Date: 2026-01-30 17:15:33.564279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65bc969cc9a2'
down_revision = '09e97b1b57ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('level_roles')]

    if 'band' not in columns:
        with op.batch_alter_table('level_roles', schema=None) as batch_op:
            batch_op.add_column(sa.Column('band', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('level_roles', schema=None) as batch_op:
        batch_op.drop_column('band')

    # ### end Alembic commands ###
