"""add credential to OwnerMeetingRoles

Revision ID: 664eb3ab47c1
Revises: c209f1d23a39
Create Date: 2026-01-26 11:01:56.493722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664eb3ab47c1'
down_revision = 'c209f1d23a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner_meeting_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credential', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner_meeting_roles', schema=None) as batch_op:
        batch_op.drop_column('credential')

    # ### end Alembic commands ###
