"""convert_roster_ticket_to_fk

Revision ID: 6666960f33dc
Revises: 5c1ba5ae90d2
Create Date: 2026-01-19 14:33:27.502645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6666960f33dc'
down_revision = '5c1ba5ae90d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('roster')]
    
    # 1. Add new column ticket_id
    if 'ticket_id' not in columns:
        with op.batch_alter_table('roster', schema=None) as batch_op:
            batch_op.add_column(sa.Column('ticket_id', sa.Integer(), nullable=True))

    # 2. Data Migration
    # Standardize legacy ticket names in 'roster.ticket' string column first
    if 'ticket' in columns:
        op.execute("UPDATE roster SET ticket = 'Early-bird (Member)' WHERE ticket = 'Early-bird' AND contact_type = 'Member'")
        op.execute("UPDATE roster SET ticket = 'Early-bird (Guest)' WHERE ticket = 'Early-bird' AND (contact_type != 'Member' OR contact_type IS NULL)")
        op.execute("UPDATE roster SET ticket = 'Walk-in (Member)' WHERE ticket = 'Walk-in' AND contact_type = 'Member'")
        op.execute("UPDATE roster SET ticket = 'Walk-in (Guest)' WHERE ticket = 'Walk-in' AND (contact_type != 'Member' OR contact_type IS NULL)")
        op.execute("UPDATE roster SET ticket = 'Voucher' WHERE ticket = 'Coupon'")
        
        # Populate ticket_id by joining with tickets table
        op.execute("""
            UPDATE roster r 
            INNER JOIN tickets t ON r.ticket = t.name 
            SET r.ticket_id = t.id
        """)

    # 3. Drop old column and add FK constraint
    fks = inspector.get_foreign_keys('roster')
    fk_name = op.f('fk_roster_ticket_id_tickets')
    fk_exists = any(fk['name'] == fk_name for fk in fks)

    with op.batch_alter_table('roster', schema=None) as batch_op:
        if not fk_exists:
            batch_op.create_foreign_key(fk_name, 'tickets', ['ticket_id'], ['id'])
        if 'ticket' in columns:
            batch_op.drop_column('ticket')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket', mysql.VARCHAR(length=20), nullable=True))
    
    # Reverse data migration (approximate)
    op.execute("""
        UPDATE roster r 
        INNER JOIN tickets t ON r.ticket_id = t.id 
        SET r.ticket = t.name
    """)

    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_roster_ticket_id_tickets'), type_='foreignkey')
        batch_op.drop_column('ticket_id')
    # ### end Alembic commands ###
