"""drop club column from contact

Revision ID: 67373574af48
Revises: e64ca3cd6a87
Create Date: 2026-01-16 21:59:44.708982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67373574af48'
down_revision = 'e64ca3cd6a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.drop_column('Club')

    with op.batch_alter_table('auth_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_roles_name'), ['name'], unique=True)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))

    with op.batch_alter_table('auth_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_roles_name'))

    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Club', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
