"""Add meeting_id to session_logs, planner, roster, and votes

Revision ID: 6dc275223ba7
Revises: f68363777405
Create Date: 2026-02-12 15:40:20.377269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc275223ba7'
down_revision = 'f68363777405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Session_Logs_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_Session_Logs_meeting_id_Meetings'), 'Meetings', ['meeting_id'], ['id'])

    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_planner_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_planner_meeting_id_Meetings'), 'Meetings', ['meeting_id'], ['id'])

    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_roster_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_roster_meeting_id_Meetings'), 'Meetings', ['meeting_id'], ['id'])

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_votes_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_votes_meeting_id_Meetings'), 'Meetings', ['meeting_id'], ['id'])

    # Data migration
    op.execute("""
        UPDATE Session_Logs sl
        JOIN Meetings m ON sl.Meeting_Number = m.Meeting_Number 
        SET sl.meeting_id = m.id
    """)
    op.execute("""
        UPDATE planner p
        JOIN Meetings m ON p.meeting_number = m.Meeting_Number 
        SET p.meeting_id = m.id
    """)
    op.execute("""
        UPDATE roster r
        JOIN Meetings m ON r.meeting_number = m.Meeting_Number 
        SET r.meeting_id = m.id
    """)
    op.execute("""
        UPDATE votes v
        JOIN Meetings m ON v.meeting_number = m.Meeting_Number 
        SET v.meeting_id = m.id
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_votes_meeting_id_Meetings'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_votes_meeting_id'))
        batch_op.drop_column('meeting_id')

    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_roster_meeting_id_Meetings'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_roster_meeting_id'))
        batch_op.drop_column('meeting_id')

    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_planner_meeting_id_Meetings'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_planner_meeting_id'))
        batch_op.drop_column('meeting_id')

    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_Session_Logs_meeting_id_Meetings'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Session_Logs_meeting_id'))
        batch_op.drop_column('meeting_id')

    # ### end Alembic commands ###
