"""set default of duration min to 0

Revision ID: 7064d9c78574
Revises: 5dc9af13d244
Create Date: 2025-11-14 17:12:22.030555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7064d9c78574'
down_revision = '5dc9af13d244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE Session_Logs SET Duration_Min = 0 WHERE Duration_Min IS NULL")

    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.alter_column('Duration_Min',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.alter_column('Duration_Min',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
