"""Add status field to pathways

Revision ID: 7377df54272a
Revises: 03cd2c1afddc
Create Date: 2025-12-29 15:28:02.828412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7377df54272a'
down_revision = '03cd2c1afddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pathways', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('active', 'inactive', 'obsolete', name='pathway_status_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pathways', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
