"""add default_awards to club

Revision ID: 73cd73774ebe
Revises: 246787f54c75
Create Date: 2026-06-16 16:45:24.539082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cd73774ebe'
down_revision = '246787f54c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_awards', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('default_awards')
    # ### end Alembic commands ###
