"""Add Club and ExComm models for multi-club support

Revision ID: 74f4cf30ecc0
Revises: c6c74fed835c
Create Date: 2026-01-16 09:57:58.797317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f4cf30ecc0'
down_revision = 'c6c74fed835c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create clubs table WITHOUT the foreign key to excomm first
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_no', sa.String(length=20), nullable=False),
    sa.Column('club_name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('division', sa.String(length=50), nullable=True),
    sa.Column('area', sa.String(length=50), nullable=True),
    sa.Column('club_address', sa.Text(), nullable=True),
    sa.Column('meeting_date', sa.String(length=100), nullable=True),
    sa.Column('meeting_time', sa.Time(), nullable=True),
    sa.Column('contact_phone_number', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('current_excomm_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clubs_club_no'), ['club_no'], unique=True)

    # Now create excomm table with foreign key to clubs
    op.create_table('excomm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('excomm_term', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('excomm_name', sa.String(length=100), nullable=True),
    sa.Column('president_id', sa.Integer(), nullable=True),
    sa.Column('vpe_id', sa.Integer(), nullable=True),
    sa.Column('vpm_id', sa.Integer(), nullable=True),
    sa.Column('vppr_id', sa.Integer(), nullable=True),
    sa.Column('secretary_id', sa.Integer(), nullable=True),
    sa.Column('treasurer_id', sa.Integer(), nullable=True),
    sa.Column('saa_id', sa.Integer(), nullable=True),
    sa.Column('ipp_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['president_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['saa_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['ipp_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['secretary_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['treasurer_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['vpe_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['vpm_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['vppr_id'], ['Contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('excomm', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excomm_excomm_term'), ['excomm_term'], unique=False)

    # Finally, add the foreign key from clubs to excomm
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_clubs_current_excomm', 'excomm', ['current_excomm_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key from clubs to excomm first
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_clubs_current_excomm', type_='foreignkey')
    
    # Drop excomm table
    with op.batch_alter_table('excomm', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_excomm_excomm_term'))

    op.drop_table('excomm')
    
    # Drop clubs table
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clubs_club_no'))

    op.drop_table('clubs')
    # ### end Alembic commands ###
