"""Rename Meetings.ID to id

Revision ID: 785f9339c40e
Revises: 1da845e56e6a
Create Date: 2025-12-29 21:07:27.884530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '785f9339c40e'
down_revision = '1da845e56e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        batch_op.alter_column('ID', new_column_name='id', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        batch_op.alter_column('id', new_column_name='ID', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###
