"""drop deprecated columns from session_logs

Revision ID: 7ce85929b05f
Revises: e1c5a73c4864
Create Date: 2026-01-23 16:17:27.431185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ce85929b05f'
down_revision = 'e1c5a73c4864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('Session_Logs')]
    fks = inspector.get_foreign_keys('Session_Logs')
    
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        fk_name = batch_op.f('fk_owner')
        if any(fk['name'] == fk_name for fk in fks):
            batch_op.drop_constraint(fk_name, type_='foreignkey')
        
        if 'Owner_ID' in columns:
            batch_op.drop_column('Owner_ID')
        if 'credentials' in columns:
            batch_op.drop_column('credentials')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credentials', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('Owner_ID', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_owner'), 'Contacts', ['Owner_ID'], ['id'])

    # ### end Alembic commands ###
