"""drop deprecated columns from session_logs

Revision ID: 7ce85929b05f
Revises: e1c5a73c4864
Create Date: 2026-01-23 16:17:27.431185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ce85929b05f'
down_revision = 'e1c5a73c4864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_owner'), type_='foreignkey')
        batch_op.drop_column('Owner_ID')
        batch_op.drop_column('credentials')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credentials', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('Owner_ID', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_owner'), 'Contacts', ['Owner_ID'], ['id'])

    # ### end Alembic commands ###
