"""add contact_id to user_clubs

Revision ID: 87b7a610c0d4
Revises: dc51ad7640b3
Create Date: 2026-01-17 02:35:48.335954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b7a610c0d4'
down_revision = 'dc51ad7640b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add contact_id to user_clubs
    with op.batch_alter_table('user_clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_clubs_contact', 'Contacts', ['contact_id'], ['id'], ondelete='CASCADE')

    # Data population: Fill user_clubs.contact_id from Users.Contact_ID
    op.execute("""
        UPDATE user_clubs
        JOIN Users ON user_clubs.user_id = Users.id
        SET user_clubs.contact_id = Users.Contact_ID
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_clubs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_clubs_contact', type_='foreignkey')
        batch_op.drop_column('contact_id')

    # ### end Alembic commands ###
