"""add contact_id to user_clubs

Revision ID: 87b7a610c0d4
Revises: dc51ad7640b3
Create Date: 2026-01-17 02:35:48.335954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b7a610c0d4'
down_revision = 'dc51ad7640b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # Check user_clubs columns
    uc_columns = [c['name'] for c in inspector.get_columns('user_clubs')]
    if 'contact_id' not in uc_columns:
        # Add contact_id to user_clubs
        with op.batch_alter_table('user_clubs', schema=None) as batch_op:
            batch_op.add_column(sa.Column('contact_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_user_clubs_contact', 'Contacts', ['contact_id'], ['id'], ondelete='CASCADE')

    # Data population: Fill user_clubs.contact_id from Users.Contact_ID
    # Only if Users have Contact_ID
    u_columns = [c['name'] for c in inspector.get_columns('Users')]
    has_contact_id = any(c.lower() == 'contact_id' for c in u_columns)
    
    if has_contact_id:
        op.execute("""
            UPDATE user_clubs
            JOIN Users ON user_clubs.user_id = Users.id
            SET user_clubs.contact_id = Users.Contact_ID
        """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_clubs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_clubs_contact', type_='foreignkey')
        batch_op.drop_column('contact_id')

    # ### end Alembic commands ###
