"""drop legacy meeting_number columns

Revision ID: 8ca4df2d75ce
Revises: 5cd5450f741a
Create Date: 2026-02-12 20:40:47.209016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ca4df2d75ce'
down_revision = '5cd5450f741a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.alter_column('Meeting_Number',
               existing_type=mysql.SMALLINT(unsigned=True),
               nullable=True)
        batch_op.drop_index(batch_op.f('fk_Session_Logs_Meeting_Number_Meetings'))

    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.alter_column('meeting_number',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('meeting_number',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_meeting_voter'))
        batch_op.create_index('idx_meeting_voter', ['meeting_id', 'voter_identifier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index('idx_meeting_voter')
        batch_op.create_index(batch_op.f('idx_meeting_voter'), ['meeting_number', 'voter_identifier'], unique=False)
        batch_op.alter_column('meeting_number',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.alter_column('meeting_number',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('fk_Session_Logs_Meeting_Number_Meetings'), ['Meeting_Number'], unique=False)
        batch_op.alter_column('Meeting_Number',
               existing_type=mysql.SMALLINT(unsigned=True),
               nullable=False)

    # ### end Alembic commands ###
