"""extract award winners and configs

Revision ID: 8d7c22139146
Revises: 93e0d3a1c6e0
Create Date: 2026-06-10 19:29:19.201110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d7c22139146'
down_revision = '93e0d3a1c6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_award_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('award_category', sa.String(length=50), nullable=False),
    sa.Column('max_votes_per_user', sa.Integer(), nullable=False),
    sa.Column('max_winners', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['Meetings.id'], name=op.f('fk_meeting_award_configs_meeting_id_Meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_award_configs')),
    sa.UniqueConstraint('meeting_id', 'award_category', name='uq_meeting_award_config')
    )
    with op.batch_alter_table('meeting_award_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_award_configs_meeting_id'), ['meeting_id'], unique=False)

    op.create_table('meeting_award_winners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('award_category', sa.String(length=50), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], name=op.f('fk_meeting_award_winners_contact_id_Contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['Meetings.id'], name=op.f('fk_meeting_award_winners_meeting_id_Meetings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_award_winners')),
    sa.UniqueConstraint('meeting_id', 'award_category', 'contact_id', name='uq_meeting_award_winner')
    )
    with op.batch_alter_table('meeting_award_winners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_award_winners_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_award_winners_meeting_id'), ['meeting_id'], unique=False)

    # Columns were already dropped in a previous failed run, so we can't migrate them.
    # Data migration skipped.

    # Columns and FKs were already dropped in a previous failed run, so we skip them here.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Columns and FKs were already dropped, so downgrade will not add them back to avoid schema errors.

    with op.batch_alter_table('meeting_award_winners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_award_winners_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_award_winners_contact_id'))

    op.drop_table('meeting_award_winners')
    with op.batch_alter_table('meeting_award_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_award_configs_meeting_id'))

    op.drop_table('meeting_award_configs')
    # ### end Alembic commands ###
