"""add subtitle to meeting table

Revision ID: 8de2f381cd37
Revises: 032e75c6fedf
Create Date: 2025-11-14 22:28:33.030440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de2f381cd37'
down_revision = '032e75c6fedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Subtitle', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        batch_op.drop_column('Subtitle')

    # ### end Alembic commands ###
