"""add_index_to_roster_contact_id

Revision ID: 8ee6d55c184f
Revises: 9f8a7b6c5d4e
Create Date: 2026-06-07 14:59:52.723293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee6d55c184f'
down_revision = '9f8a7b6c5d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roster_contact_id'), ['contact_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roster_contact_id'))

    # ### end Alembic commands ###
