"""add club_id to auth_roles

Revision ID: 9023be6a588b
Revises: e4f053c6e5d3
Create Date: 2026-05-25 18:27:05.548035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9023be6a588b'
down_revision = 'e4f053c6e5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests')
    with op.batch_alter_table('auth_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_auth_roles_name'))
        batch_op.create_index(batch_op.f('ix_auth_roles_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_roles_club_id'), ['club_id'], unique=False)
        batch_op.create_unique_constraint('uq_club_role_name', ['club_id', 'name'])
        batch_op.create_foreign_key(batch_op.f('fk_auth_roles_club_id_clubs'), 'clubs', ['club_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_clubs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_clubs_auth_role'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_clubs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_clubs_auth_role'), ['auth_role_id'], unique=False)

    with op.batch_alter_table('auth_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_auth_roles_club_id_clubs'), type_='foreignkey')
        batch_op.drop_constraint('uq_club_role_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_auth_roles_club_id'))
        batch_op.drop_index(batch_op.f('ix_auth_roles_name'))
        batch_op.create_index(batch_op.f('ix_auth_roles_name'), ['name'], unique=True)
        batch_op.drop_column('club_id')

    op.create_table('guests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('club_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_date', mysql.DATETIME(), nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_guests_club_id_clubs')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guests_club_id'), ['club_id'], unique=False)

    # ### end Alembic commands ###
