"""Rename Completed_Levels to Completed_Paths in Contact table

Revision ID: 9c0d4e2355b3
Revises: cc3d020320b4
Create Date: 2025-11-23 14:26:06.527819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c0d4e2355b3'
down_revision = 'cc3d020320b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.alter_column('Completed_Levels', 
                              new_column_name='Completed_Paths',
                              existing_type=sa.String(255),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.alter_column('Completed_Paths',
                              new_column_name='Completed_Levels',
                              existing_type=sa.String(255),
                              nullable=True)
    # ### end Alembic commands ###