"""Seed pathway_projects data

Revision ID: 9c6737b06886
Revises: 4c34ee4b927d
Create Date: 2025-12-03 16:18:09.492855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Enum


# revision identifiers, used by Alembic.
revision = '9c6737b06886'
down_revision = '4c34ee4b927d'
branch_labels = None
depends_on = None


def upgrade():
    pathway_type_enum = Enum('elective', 'required',
                             'other', name='pathway_project_type_enum')
    pathway_type_enum.create(op.get_bind(), checkfirst=True)  # Safe creation

    op.add_column('pathway_projects',
                  sa.Column('type', pathway_type_enum,
                            nullable=False, server_default='required')
                  )

    pathway_projects_table = table('pathway_projects',
                                   column('path_id', Integer),
                                   column('project_id', Integer),
                                   column('code', String),
                                   column('type', Enum('elective', 'required',
                                                       'other', name='project_type_enum'))
                                   )

    data_to_insert = [
        {'path_id': 1, 'project_id': 1, 'code': '1.1', 'type': 'required'},
        {'path_id': 1, 'project_id': 2, 'code': '1.2', 'type': 'required'},
        {'path_id': 1, 'project_id': 3, 'code': '1.3', 'type': 'required'},
        {'path_id': 1, 'project_id': 4, 'code': '1.4.1', 'type': 'required'},
        {'path_id': 1, 'project_id': 5, 'code': '1.4.2', 'type': 'required'},
        {'path_id': 1, 'project_id': 6, 'code': '1.4.3', 'type': 'required'},
        {'path_id': 1, 'project_id': 7, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 8, 'code': '2.2', 'type': 'required'},
        {'path_id': 1, 'project_id': 9, 'code': '2.1', 'type': 'required'},
        {'path_id': 1, 'project_id': 10, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 11, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 12, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 13, 'code': '2.3', 'type': 'required'},
        {'path_id': 1, 'project_id': 16, 'code': '3.1', 'type': 'required'},
        {'path_id': 1, 'project_id': 20, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 21, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 22, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 23, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 24, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 25, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 26, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 27, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 28, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 29, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 30, 'code': '3.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 33, 'code': '4.1', 'type': 'required'},
        {'path_id': 1, 'project_id': 37, 'code': '4.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 38, 'code': '4.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 39, 'code': '4.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 40, 'code': '4.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 41, 'code': '4.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 42, 'code': '4.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 43, 'code': '4.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 44, 'code': '4.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 48, 'code': '5.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 49, 'code': '5.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 50, 'code': '5.1', 'type': 'required'},
        {'path_id': 1, 'project_id': 51, 'code': '5.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 53, 'code': '5.3', 'type': 'required'},
        {'path_id': 1, 'project_id': 54, 'code': '5.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 55, 'code': '5.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 56, 'code': '5.2', 'type': 'elective'},
        {'path_id': 1, 'project_id': 57, 'code': '5.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 1, 'code': '1.1', 'type': 'required'},
        {'path_id': 2, 'project_id': 2, 'code': '1.2', 'type': 'required'},
        {'path_id': 2, 'project_id': 3, 'code': '1.3', 'type': 'required'},
        {'path_id': 2, 'project_id': 4, 'code': '1.4.1', 'type': 'required'},
        {'path_id': 2, 'project_id': 5, 'code': '1.4.2', 'type': 'required'},
        {'path_id': 2, 'project_id': 6, 'code': '1.4.3', 'type': 'required'},
        {'path_id': 2, 'project_id': 7, 'code': '2.1', 'type': 'required'},
        {'path_id': 2, 'project_id': 10, 'code': '3.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 11, 'code': '2.2', 'type': 'required'},
        {'path_id': 2, 'project_id': 12, 'code': '3.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 13, 'code': '2.3', 'type': 'required'},
        {'path_id': 2, 'project_id': 15, 'code': '3.1', 'type': 'required'},
        {'path_id': 2, 'project_id': 20, 'code': '3.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 21, 'code': '3.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 22, 'code': '3.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 23, 'code': '3.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 24, 'code': '3.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 25, 'code': '3.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 26, 'code': '3.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 27, 'code': '3.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 28, 'code': '3.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 29, 'code': '3.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 30, 'code': '3.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 34, 'code': '4.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 36, 'code': '4.1', 'type': 'required'},
        {'path_id': 2, 'project_id': 37, 'code': '4.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 38, 'code': '4.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 39, 'code': '4.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 40, 'code': '4.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 41, 'code': '4.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 42, 'code': '4.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 43, 'code': '4.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 44, 'code': '4.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 45, 'code': '5.1', 'type': 'required'},
        {'path_id': 2, 'project_id': 48, 'code': '5.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 49, 'code': '5.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 51, 'code': '5.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 53, 'code': '5.3', 'type': 'required'},
        {'path_id': 2, 'project_id': 54, 'code': '5.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 55, 'code': '5.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 56, 'code': '5.2', 'type': 'elective'},
        {'path_id': 2, 'project_id': 57, 'code': '5.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 1, 'code': '1.1', 'type': 'required'},
        {'path_id': 3, 'project_id': 2, 'code': '1.2', 'type': 'required'},
        {'path_id': 3, 'project_id': 3, 'code': '1.3', 'type': 'required'},
        {'path_id': 3, 'project_id': 4, 'code': '1.4.1', 'type': 'required'},
        {'path_id': 3, 'project_id': 5, 'code': '1.4.2', 'type': 'required'},
        {'path_id': 3, 'project_id': 6, 'code': '1.4.3', 'type': 'required'},
        {'path_id': 3, 'project_id': 7, 'code': '3.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 8, 'code': '2.1', 'type': 'required'},
        {'path_id': 3, 'project_id': 10, 'code': '2.2', 'type': 'required'},
        {'path_id': 3, 'project_id': 11, 'code': '3.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 12, 'code': '3.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 13, 'code': '2.3', 'type': 'required'},
        {'path_id': 3, 'project_id': 19, 'code': '3.1', 'type': 'required'},
        {'path_id': 3, 'project_id': 20, 'code': '3.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 21, 'code': '3.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 22, 'code': '3.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 23, 'code': '3.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 24, 'code': '3.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 25, 'code': '3.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 26, 'code': '3.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 27, 'code': '3.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 28, 'code': '3.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 29, 'code': '3.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 30, 'code': '3.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 34, 'code': '4.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 35, 'code': '4.1', 'type': 'required'},
        {'path_id': 3, 'project_id': 37, 'code': '4.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 38, 'code': '4.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 39, 'code': '4.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 40, 'code': '4.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 41, 'code': '4.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 42, 'code': '4.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 43, 'code': '4.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 44, 'code': '4.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 48, 'code': '5.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 49, 'code': '5.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 51, 'code': '5.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 52, 'code': '5.1', 'type': 'required'},
        {'path_id': 3, 'project_id': 53, 'code': '5.3', 'type': 'required'},
        {'path_id': 3, 'project_id': 54, 'code': '5.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 55, 'code': '5.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 56, 'code': '5.2', 'type': 'elective'},
        {'path_id': 3, 'project_id': 57, 'code': '5.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 1, 'code': '1.1', 'type': 'required'},
        {'path_id': 4, 'project_id': 2, 'code': '1.2', 'type': 'required'},
        {'path_id': 4, 'project_id': 3, 'code': '1.3', 'type': 'required'},
        {'path_id': 4, 'project_id': 4, 'code': '1.4.1', 'type': 'required'},
        {'path_id': 4, 'project_id': 5, 'code': '1.4.2', 'type': 'required'},
        {'path_id': 4, 'project_id': 6, 'code': '1.4.3', 'type': 'required'},
        {'path_id': 4, 'project_id': 7, 'code': '3.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 9, 'code': '2.1', 'type': 'required'},
        {'path_id': 4, 'project_id': 10, 'code': '2.2', 'type': 'required'},
        {'path_id': 4, 'project_id': 11, 'code': '3.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 12, 'code': '3.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 13, 'code': '2.3', 'type': 'required'},
        {'path_id': 4, 'project_id': 18, 'code': '3.1', 'type': 'required'},
        {'path_id': 4, 'project_id': 20, 'code': '3.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 21, 'code': '3.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 22, 'code': '3.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 23, 'code': '3.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 24, 'code': '3.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 25, 'code': '3.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 26, 'code': '3.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 27, 'code': '3.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 28, 'code': '3.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 29, 'code': '3.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 30, 'code': '3.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 32, 'code': '4.1', 'type': 'required'},
        {'path_id': 4, 'project_id': 37, 'code': '4.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 38, 'code': '4.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 39, 'code': '4.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 40, 'code': '4.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 41, 'code': '4.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 42, 'code': '4.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 43, 'code': '4.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 44, 'code': '4.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 48, 'code': '5.1', 'type': 'required'},
        {'path_id': 4, 'project_id': 49, 'code': '5.1', 'type': 'required'},
        {'path_id': 4, 'project_id': 51, 'code': '5.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 53, 'code': '5.3', 'type': 'required'},
        {'path_id': 4, 'project_id': 54, 'code': '5.1', 'type': 'required'},
        {'path_id': 4, 'project_id': 55, 'code': '5.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 56, 'code': '5.2', 'type': 'elective'},
        {'path_id': 4, 'project_id': 57, 'code': '5.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 1, 'code': '1.1', 'type': 'required'},
        {'path_id': 5, 'project_id': 2, 'code': '1.2', 'type': 'required'},
        {'path_id': 5, 'project_id': 3, 'code': '1.3', 'type': 'required'},
        {'path_id': 5, 'project_id': 4, 'code': '1.4.1', 'type': 'required'},
        {'path_id': 5, 'project_id': 5, 'code': '1.4.2', 'type': 'required'},
        {'path_id': 5, 'project_id': 6, 'code': '1.4.3', 'type': 'required'},
        {'path_id': 5, 'project_id': 7, 'code': '3.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 8, 'code': '2.1', 'type': 'required'},
        {'path_id': 5, 'project_id': 10, 'code': '3.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 11, 'code': '3.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 12, 'code': '2.2', 'type': 'required'},
        {'path_id': 5, 'project_id': 13, 'code': '2.3', 'type': 'required'},
        {'path_id': 5, 'project_id': 17, 'code': '3.1', 'type': 'required'},
        {'path_id': 5, 'project_id': 20, 'code': '3.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 21, 'code': '3.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 22, 'code': '3.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 23, 'code': '3.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 24, 'code': '3.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 25, 'code': '3.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 26, 'code': '3.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 27, 'code': '3.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 28, 'code': '3.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 29, 'code': '3.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 30, 'code': '3.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 34, 'code': '4.1', 'type': 'required'},
        {'path_id': 5, 'project_id': 37, 'code': '4.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 38, 'code': '4.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 39, 'code': '4.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 40, 'code': '4.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 41, 'code': '4.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 43, 'code': '4.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 44, 'code': '4.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 48, 'code': '5.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 49, 'code': '5.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 51, 'code': '5.1', 'type': 'required'},
        {'path_id': 5, 'project_id': 53, 'code': '5.3', 'type': 'required'},
        {'path_id': 5, 'project_id': 54, 'code': '5.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 55, 'code': '5.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 56, 'code': '5.2', 'type': 'elective'},
        {'path_id': 5, 'project_id': 57, 'code': '5.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 1, 'code': '1.1', 'type': 'required'},
        {'path_id': 6, 'project_id': 2, 'code': '1.2', 'type': 'required'},
        {'path_id': 6, 'project_id': 3, 'code': '1.3', 'type': 'required'},
        {'path_id': 6, 'project_id': 4, 'code': '1.4.1', 'type': 'required'},
        {'path_id': 6, 'project_id': 5, 'code': '1.4.2', 'type': 'required'},
        {'path_id': 6, 'project_id': 6, 'code': '1.4.3', 'type': 'required'},
        {'path_id': 6, 'project_id': 7, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 8, 'code': '2.2', 'type': 'required'},
        {'path_id': 6, 'project_id': 9, 'code': '2.1', 'type': 'required'},
        {'path_id': 6, 'project_id': 10, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 11, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 12, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 13, 'code': '2.3', 'type': 'required'},
        {'path_id': 6, 'project_id': 14, 'code': '3.1', 'type': 'required'},
        {'path_id': 6, 'project_id': 20, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 21, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 22, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 23, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 24, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 25, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 26, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 27, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 28, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 29, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 30, 'code': '3.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 31, 'code': '4.1', 'type': 'required'},
        {'path_id': 6, 'project_id': 37, 'code': '4.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 38, 'code': '4.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 39, 'code': '4.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 40, 'code': '4.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 41, 'code': '4.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 42, 'code': '4.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 43, 'code': '4.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 44, 'code': '4.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 46, 'code': '5.1.1', 'type': 'required'},
        {'path_id': 6, 'project_id': 47, 'code': '5.1.2', 'type': 'required'},
        {'path_id': 6, 'project_id': 48, 'code': '5.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 49, 'code': '5.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 51, 'code': '5.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 53, 'code': '5.3', 'type': 'required'},
        {'path_id': 6, 'project_id': 54, 'code': '5.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 55, 'code': '5.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 56, 'code': '5.2', 'type': 'elective'},
        {'path_id': 6, 'project_id': 57, 'code': '5.2', 'type': 'elective'},
        {'path_id': 7, 'project_id': 58, 'code': '1.1', 'type': 'required'},
        {'path_id': 7, 'project_id': 59, 'code': '1.2', 'type': 'required'},
        {'path_id': 8, 'project_id': 60, 'code': '1.0', 'type': 'other'},
    ]

    op.bulk_insert(pathway_projects_table, data_to_insert)


def downgrade():
    # Optional: Delete data if you downgrade
    op.execute("DELETE FROM pathway_projects")
    op.drop_column('pathway_projects', 'type')
    pathway_type_enum = Enum('elective', 'required',
                             'other', name='pathway_project_type_enum')
    pathway_type_enum.drop(op.get_bind(), checkfirst=True)
