"""add is_connected to contacts

Revision ID: 9d6de2854377
Revises: ca2c3bedf364
Create Date: 2026-01-30 01:37:46.970108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6de2854377'
down_revision = 'ca2c3bedf364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_connected', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE Contacts SET is_connected = 1")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.drop_column('is_connected')

    # ### end Alembic commands ###
