"""Add level column to PathwayProject

Revision ID: 9e307299fdce
Revises: ea9351d03692
Create Date: 2025-12-29 02:37:04.834104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e307299fdce'
down_revision = 'ea9351d03692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pathway_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pathway_projects', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
