"""add avatar_url to contact

Revision ID: a4780e9744df
Revises: 0d317a79108e
Create Date: 2025-12-30 16:26:00.498673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4780e9744df'
down_revision = '0d317a79108e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Avatar_URL', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.drop_column('Avatar_URL')

    # ### end Alembic commands ###
