"""Add profile columns to Contact

Revision ID: a74d17f36522
Revises: 440e33f9ebf3
Create Date: 2025-12-26 12:40:18.758030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a74d17f36522'
down_revision = '440e33f9ebf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Member_ID', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('Mentor_ID', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Current_Path', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('Next_Project', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('credentials', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(None, ['Member_ID'])
        batch_op.create_foreign_key(None, 'Contacts', ['Mentor_ID'], ['id'])

    # Removed noise changes for Meetings, Projects, etc.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('credentials')
        batch_op.drop_column('Next_Project')
        batch_op.drop_column('Current_Path')
        batch_op.drop_column('Mentor_ID')
        batch_op.drop_column('Member_ID')

    # ### end Alembic commands ###

    # ### end Alembic commands ###
