"""remove default_owner from session_types

Revision ID: a7d46f73c689
Revises: c8e68f6094f6
Create Date: 2026-01-27 16:47:29.629490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7d46f73c689'
down_revision = 'c8e68f6094f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('Session_Types')]

    if 'Default_Owner' in columns:
        with op.batch_alter_table('Session_Types', schema=None) as batch_op:
            batch_op.drop_column('Default_Owner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Default_Owner', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
