"""Add title to Planner

Revision ID: ae21f894f8df
Revises: f9af03b411b2
Create Date: 2026-03-02 10:22:05.198193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae21f894f8df'
down_revision = 'f9af03b411b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
