"""add user_clubs association table

Revision ID: b039865b5938
Revises: d0dbd94d30f9
Create Date: 2026-01-17 00:57:13.394048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b039865b5938'
down_revision = 'd0dbd94d30f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'user_clubs' not in tables:
        op.create_table('user_clubs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('club_id', sa.Integer(), nullable=False),
        sa.Column('club_role_id', sa.Integer(), nullable=True),
        sa.Column('current_path_id', sa.Integer(), nullable=True),
        sa.Column('joined_date', sa.Date(), nullable=True),
        sa.Column('is_home', sa.Boolean(), nullable=False),
        sa.Column('mentor_id', sa.Integer(), nullable=True),
        sa.Column('next_project_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['current_path_id'], ['pathways.id'], ),
        sa.ForeignKeyConstraint(['mentor_id'], ['Contacts.id'], ),
        sa.ForeignKeyConstraint(['next_project_id'], ['Projects.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'club_id', name='uq_user_club')
        )
        with op.batch_alter_table('user_clubs', schema=None) as batch_op:
            batch_op.create_index('ix_user_clubs_club', ['club_id'], unique=False)
            batch_op.create_index('ix_user_clubs_user', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Indexes will be automatically dropped when the table is dropped,
    # so we don't need to explicitly drop them (and doing so causes errors
    # because MySQL won't drop an index that's needed by a foreign key)
    op.drop_table('user_clubs')
    # ### end Alembic commands ###
