"""add target_pathway and target_level to owner_meeting_roles

Revision ID: b386d5c209e9
Revises: 98391280144b
Create Date: 2026-05-20 00:39:52.586869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b386d5c209e9'
down_revision = '98391280144b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner_meeting_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_pathway', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('target_level', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner_meeting_roles', schema=None) as batch_op:
        batch_op.drop_column('target_level')
        batch_op.drop_column('target_pathway')
    # ### end Alembic commands ###
