"""create_contact_clubs_table

Revision ID: bd35dd8fa024
Revises: 98c58724d0bb
Create Date: 2026-01-16 17:23:13.638829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd35dd8fa024'
down_revision = '98c58724d0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('membership_type', sa.String(length=50), nullable=True),
    sa.Column('joined_date', sa.Date(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'club_id', name='uq_contact_club')
    )
    with op.batch_alter_table('contact_clubs', schema=None) as batch_op:
        batch_op.create_index('ix_contact_clubs_club', ['club_id'], unique=False)
        batch_op.create_index('ix_contact_clubs_contact', ['contact_id'], unique=False)

    # Populate contact_clubs with existing contacts assigned to the first club
    from sqlalchemy import text
    conn = op.get_bind()
    
    # Get the default club ID
    result = conn.execute(text("SELECT id FROM clubs LIMIT 1"))
    club_row = result.fetchone()
    
    if club_row:
        default_club_id = club_row[0]
        # Assign all contacts to this default club as primary members
        conn.execute(text(f"""
            INSERT INTO contact_clubs (contact_id, club_id, membership_type, is_primary, created_at, updated_at)
            SELECT id, {default_club_id}, 'Member', 1, NOW(), NOW()
            FROM Contacts
            WHERE id NOT IN (SELECT contact_id FROM contact_clubs WHERE club_id = {default_club_id})
        """))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_clubs')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
