"""remove Working_Path and Next_Path from Contact model

Revision ID: c5304a5ed264
Revises: e4925d83d820
Create Date: 2025-11-16 22:05:42.571029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5304a5ed264'
down_revision = 'e4925d83d820'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.drop_column('Next_Project')
        batch_op.drop_column('Working_Path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Working_Path', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('Next_Project', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
