"""remove predefined from session types

Revision ID: c8e68f6094f6
Revises: 664eb3ab47c1
Create Date: 2026-01-27 16:34:58.086345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8e68f6094f6'
down_revision = '664eb3ab47c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('Session_Types')]

    if 'Predefined' in columns:
        with op.batch_alter_table('Session_Types', schema=None) as batch_op:
            batch_op.drop_column('Predefined')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Predefined', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
