"""add session_log hidden column

Revision ID: ca2c3bedf364
Revises: 58e5efb96174
Create Date: 2026-01-28 16:45:36.238194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2c3bedf364'
down_revision = '58e5efb96174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('Session_Logs')]
    
    if 'hidden' not in columns:
        with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
            batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))

        # Backfill data based on SessionType.Is_Hidden
        conn.execute(
            sa.text("""
            UPDATE Session_Logs sl
            JOIN Session_Types st ON sl.Type_ID = st.id
            SET sl.hidden = st.Is_Hidden
            """)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
