"""Add Credential field to User table

Revision ID: cc3d020320b4
Revises: c0258c34dcb6
Create Date: 2025-11-23 14:21:04.660830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3d020320b4'
down_revision = 'c0258c34dcb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Credential', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('Credential')

    # ### end Alembic commands ###
