"""rename current_path_level to project_code

Revision ID: d2039c1c5357
Revises: 59e4cd3ff135
Create Date: 2026-01-01 17:28:25.260201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2039c1c5357'
down_revision = '59e4cd3ff135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.alter_column('current_path_level', new_column_name='project_code', existing_type=sa.String(length=10))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.alter_column('project_code', new_column_name='current_path_level', existing_type=sa.String(length=10))

    # ### end Alembic commands ###
