"""Add status field to Meeting table

Revision ID: d44b399886f5
Revises: 3e5ec24b274d
Create Date: 2025-11-24 18:01:00.173464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd44b399886f5'
down_revision = '3e5ec24b274d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('not started', 'running', 'finished', 'cancelled', name='meeting_status'), nullable=False))

    with op.batch_alter_table('Session_Types', schema=None) as batch_op:
        batch_op.drop_column('Role')
        batch_op.drop_column('Role_Group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Role_Group', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('Role', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=True))

    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
