"""Remove legacy Role column from Users table

Revision ID: daec7f3551bf
Revises: b660ab1f51bb
Create Date: 2026-01-15 16:51:31.296979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'daec7f3551bf'
down_revision = 'b660ab1f51bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Create permission_audits table if it doesn't exist
    if 'permission_audits' not in existing_tables:
        op.create_table('permission_audits',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('admin_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('target_type', sa.String(length=50), nullable=False),
        sa.Column('target_id', sa.Integer(), nullable=False),
        sa.Column('target_name', sa.String(length=100), nullable=True),
        sa.Column('changes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['admin_id'], ['Users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    
    # Check if Role column exists before dropping it
    users_columns = [col['name'] for col in inspector.get_columns('Users')]
    if 'Role' in users_columns:
        with op.batch_alter_table('Users', schema=None) as batch_op:
            batch_op.drop_column('Role')

    # Handle auth_roles indexes - check if they exist before dropping
    auth_roles_indexes = {idx['name'] for idx in inspector.get_indexes('auth_roles')}
    if 'name' in auth_roles_indexes or 'ix_auth_roles_name' in auth_roles_indexes:
        with op.batch_alter_table('auth_roles', schema=None) as batch_op:
            if 'name' in auth_roles_indexes:
                batch_op.drop_index('name')
            if 'ix_auth_roles_name' in auth_roles_indexes:
                batch_op.drop_index(batch_op.f('ix_auth_roles_name'))
            # Only create if it doesn't exist
            if 'ix_auth_roles_name' not in auth_roles_indexes:
                batch_op.create_index(batch_op.f('ix_auth_roles_name'), ['name'], unique=True)

    # Handle permissions indexes - check if they exist before dropping
    permissions_indexes = {idx['name'] for idx in inspector.get_indexes('permissions')}
    if 'name' in permissions_indexes or 'ix_permissions_name' in permissions_indexes:
        with op.batch_alter_table('permissions', schema=None) as batch_op:
            if 'name' in permissions_indexes:
                batch_op.drop_index('name')
            if 'ix_permissions_name' in permissions_indexes:
                batch_op.drop_index(batch_op.f('ix_permissions_name'))
            # Only create if it doesn't exist
            if 'ix_permissions_name' not in permissions_indexes:
                batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    # Handle roster table - check if order_number column needs to be altered
    if 'roster' in existing_tables:
        roster_columns = {col['name']: col for col in inspector.get_columns('roster')}
        if 'order_number' in roster_columns and roster_columns['order_number'].get('nullable') == False:
            with op.batch_alter_table('roster', schema=None) as batch_op:
                batch_op.alter_column('order_number',
                       existing_type=mysql.INTEGER(),
                       nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Handle roster table - only alter if it exists and column is nullable
    if 'roster' in existing_tables:
        roster_columns = {col['name']: col for col in inspector.get_columns('roster')}
        if 'order_number' in roster_columns and roster_columns['order_number'].get('nullable') == True:
            with op.batch_alter_table('roster', schema=None) as batch_op:
                batch_op.alter_column('order_number',
                       existing_type=mysql.INTEGER(),
                       nullable=False)

    # Handle permissions indexes - check existence before dropping/creating
    if 'permissions' in existing_tables:
        permissions_indexes = {idx['name'] for idx in inspector.get_indexes('permissions')}
        if permissions_indexes:  # Only proceed if there are indexes to work with
            with op.batch_alter_table('permissions', schema=None) as batch_op:
                if 'ix_permissions_name' in permissions_indexes:
                    batch_op.drop_index(batch_op.f('ix_permissions_name'))
                    batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=False)
                if 'name' not in permissions_indexes:
                    batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    # Handle auth_roles indexes - check existence before dropping/creating
    if 'auth_roles' in existing_tables:
        auth_roles_indexes = {idx['name'] for idx in inspector.get_indexes('auth_roles')}
        if auth_roles_indexes:  # Only proceed if there are indexes to work with
            with op.batch_alter_table('auth_roles', schema=None) as batch_op:
                if 'ix_auth_roles_name' in auth_roles_indexes:
                    batch_op.drop_index(batch_op.f('ix_auth_roles_name'))
                    batch_op.create_index(batch_op.f('ix_auth_roles_name'), ['name'], unique=False)
                if 'name' not in auth_roles_indexes:
                    batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    # Add Role column back to Users if it doesn't exist
    if 'Users' in existing_tables:
        users_columns = [col['name'] for col in inspector.get_columns('Users')]
        if 'Role' not in users_columns:
            with op.batch_alter_table('Users', schema=None) as batch_op:
                batch_op.add_column(sa.Column('Role', mysql.VARCHAR(length=50), server_default=sa.text("'Member'"), nullable=False))

    # Drop permission_audits table if it exists
    if 'permission_audits' in existing_tables:
        op.drop_table('permission_audits')
    # ### end Alembic commands ###
