"""Remove legacy Role column from Users table

Revision ID: daec7f3551bf
Revises: b660ab1f51bb
Create Date: 2026-01-15 16:51:31.296979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'daec7f3551bf'
down_revision = 'b660ab1f51bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_name', sa.String(length=100), nullable=True),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('Role')

    with op.batch_alter_table('auth_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))
        batch_op.drop_index(batch_op.f('ix_auth_roles_name'))
        batch_op.create_index(batch_op.f('ix_auth_roles_name'), ['name'], unique=True)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_name'))
        batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('auth_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_roles_name'))
        batch_op.create_index(batch_op.f('ix_auth_roles_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Role', mysql.VARCHAR(length=50), server_default=sa.text("'Member'"), nullable=False))

    op.drop_table('permission_audits')
    # ### end Alembic commands ###
