"""fix projects id auto increment

Revision ID: dd8425cc0f23
Revises: 02ee44fa58f8
Create Date: 2025-12-30 11:02:54.690530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8425cc0f23'
down_revision = '02ee44fa58f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Cleanup potential Project 0 which causes conflict with AUTO_INCREMENT
    op.execute("UPDATE Session_Logs SET project_id = NULL WHERE project_id = 0")
    op.execute("DELETE FROM Projects WHERE id = 0")
    
    op.execute("SET FOREIGN_KEY_CHECKS = 0")
    op.execute("ALTER TABLE Projects MODIFY id INT NOT NULL AUTO_INCREMENT")
    op.execute("SET FOREIGN_KEY_CHECKS = 1")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SET FOREIGN_KEY_CHECKS = 0")
    op.execute("ALTER TABLE Projects MODIFY id INT NOT NULL")
    op.execute("SET FOREIGN_KEY_CHECKS = 1")
    # ### end Alembic commands ###
