"""support multiple owners for session logs

Revision ID: e1c5a73c4864
Revises: c0fd0f865e8a
Create Date: 2026-01-23 15:11:43.812742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c5a73c4864'
down_revision = 'c0fd0f865e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_log_owners',
    sa.Column('session_log_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], name=op.f('fk_session_log_owners_contact_id_Contacts')),
    sa.ForeignKeyConstraint(['session_log_id'], ['Session_Logs.id'], name=op.f('fk_session_log_owners_session_log_id_Session_Logs')),
    sa.PrimaryKeyConstraint('session_log_id', 'contact_id', name=op.f('pk_session_log_owners'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_log_owners')
    # ### end Alembic commands ###
