"""Add ticket_type to MeetingRole

Revision ID: e3a4db9468b7
Revises: c7e8f9a0b1d2
Create Date: 2026-04-08 15:34:44.408853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'e3a4db9468b7'
down_revision = 'c7e8f9a0b1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Check meeting_roles columns
    meeting_roles_columns = [c['name'] for c in inspector.get_columns('meeting_roles')]
    if 'ticket_type' not in meeting_roles_columns:
        with op.batch_alter_table('meeting_roles', schema=None) as batch_op:
            batch_op.add_column(sa.Column('ticket_type', sa.String(length=50), nullable=True))

    # Check user_clubs indices and foreign keys
    user_clubs_indexes = [i['name'] for i in inspector.get_indexes('user_clubs')]
    user_clubs_fks = [fk['name'] for fk in inspector.get_foreign_keys('user_clubs')]
    
    if 'ix_user_clubs_auth_role' in user_clubs_indexes and 'ix_user_clubs_auth_role_id' not in user_clubs_indexes:
        with op.batch_alter_table('user_clubs', schema=None) as batch_op:
            # Need to drop FK before dropping index in MySQL
            if 'fk_user_clubs_auth_role' in user_clubs_fks:
                batch_op.drop_constraint('fk_user_clubs_auth_role', type_='foreignkey')
            
            batch_op.drop_index('ix_user_clubs_auth_role')
            batch_op.create_index(batch_op.f('ix_user_clubs_auth_role_id'), ['auth_role_id'], unique=False)
            
            # Recreate FK
            batch_op.create_foreign_key('fk_user_clubs_auth_role', 'auth_roles', ['auth_role_id'], ['id'])
    elif 'ix_user_clubs_auth_role_id' not in user_clubs_indexes:
         # Just in case the old index was already gone but new one not yet created
         with op.batch_alter_table('user_clubs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_user_clubs_auth_role_id'), ['auth_role_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Check user_clubs indices and foreign keys
    user_clubs_indexes = [i['name'] for i in inspector.get_indexes('user_clubs')]
    user_clubs_fks = [fk['name'] for fk in inspector.get_foreign_keys('user_clubs')]
    
    if 'ix_user_clubs_auth_role_id' in user_clubs_indexes:
        with op.batch_alter_table('user_clubs', schema=None) as batch_op:
            if 'fk_user_clubs_auth_role' in user_clubs_fks:
                batch_op.drop_constraint('fk_user_clubs_auth_role', type_='foreignkey')
                
            batch_op.drop_index(batch_op.f('ix_user_clubs_auth_role_id'))
            batch_op.create_index('ix_user_clubs_auth_role', ['auth_role_id'], unique=False)
            
            batch_op.create_foreign_key('fk_user_clubs_auth_role', 'auth_roles', ['auth_role_id'], ['id'])

    # Check meeting_roles columns
    meeting_roles_columns = [c['name'] for c in inspector.get_columns('meeting_roles')]
    if 'ticket_type' in meeting_roles_columns:
        with op.batch_alter_table('meeting_roles', schema=None) as batch_op:
            batch_op.drop_column('ticket_type')

    # ### end Alembic commands ###
