"""Add ticket_type to MeetingRole

Revision ID: e3a4db9468b7
Revises: c7e8f9a0b1d2
Create Date: 2026-04-08 15:34:44.408853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a4db9468b7'
down_revision = 'c7e8f9a0b1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user_clubs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_clubs_auth_role'))
        batch_op.create_index(batch_op.f('ix_user_clubs_auth_role_id'), ['auth_role_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_clubs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_clubs_auth_role_id'))
        batch_op.create_index(batch_op.f('ix_user_clubs_auth_role'), ['auth_role_id'], unique=False)

    with op.batch_alter_table('meeting_roles', schema=None) as batch_op:
        batch_op.drop_column('ticket_type')

    # ### end Alembic commands ###
