"""Add role_id to roster table

Revision ID: e4b40623ff55
Revises: 78eb2339f295
Create Date: 2026-01-12 16:37:19.475942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b40623ff55'
down_revision = '78eb2339f295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_meetings_media_id', 'Media', ['media_id'], ['id'], use_alter=True)

    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_roster_role_id', 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster', schema=None) as batch_op:
        # Check if the foreign key exists before attempting to drop it
        conn = op.get_bind()
        result = conn.execute(
            "SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE "
            "WHERE TABLE_NAME='roster' AND CONSTRAINT_SCHEMA=DATABASE() AND CONSTRAINT_NAME='fk_roster_role_id'"
        )
        if result.fetchone():
            batch_op.drop_constraint('fk_roster_role_id', type_='foreignkey')
        batch_op.drop_column('role_id')

    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meetings_media_id', type_='foreignkey')

    # ### end Alembic commands ###
