"""first deployment with baseline schema 20260116

Revision ID: e64ca3cd6a87
Revises: 
Create Date: 2026-01-16 19:11:20.364578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e64ca3cd6a87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # 1. Base Tables (No dependencies)
    if not inspector.has_table('Contacts'):
        op.create_table('Contacts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('Club', sa.String(length=100), nullable=True),
        sa.Column('Name', sa.String(length=100), nullable=False),
        sa.Column('Email', sa.String(length=120), nullable=True),
        sa.Column('Type', sa.String(length=50), nullable=False, server_default='Guest'),
        sa.Column('Date_Created', sa.Date(), nullable=True),
        sa.Column('Completed_Paths', sa.String(length=255), nullable=True),
        sa.Column('DTM', sa.Boolean(), nullable=True),
        sa.Column('credentials', sa.String(length=10), nullable=True),
        sa.Column('Phone_Number', sa.String(length=50), nullable=True),
        sa.Column('Bio', sa.Text(), nullable=True),
        sa.Column('Member_ID', sa.String(length=50), nullable=True),
        sa.Column('Mentor_ID', sa.Integer(), nullable=True),
        sa.Column('Current_Path', sa.String(length=50), nullable=True),
        sa.Column('Next_Project', sa.String(length=100), nullable=True),
        sa.Column('Avatar_URL', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['Mentor_ID'], ['Contacts.id'], name='fk_Contacts_Mentor_ID_Contacts'),
        sa.PrimaryKeyConstraint('id', name='pk_Contacts')
        )

    if not inspector.has_table('Projects'):
        op.create_table('Projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('Project_Name', sa.String(length=255), nullable=False),
        sa.Column('Format', sa.String(length=50), nullable=True),
        sa.Column('Duration_Min', sa.Integer(), nullable=True),
        sa.Column('Duration_Max', sa.Integer(), nullable=True),
        sa.Column('Introduction', sa.String(length=1000), nullable=True),
        sa.Column('Overview', sa.String(length=1000), nullable=True),
        sa.Column('Purpose', sa.String(length=255), nullable=True),
        sa.Column('Requirements', sa.String(length=500), nullable=True),
        sa.Column('Resources', sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint('id', name='pk_Projects')
        )

    if not inspector.has_table('auth_roles'):
        op.create_table('auth_roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('level', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name='pk_auth_roles')
        )
        with op.batch_alter_table('auth_roles', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_auth_roles_name'), ['name'], unique=True)

    if not inspector.has_table('clubs'):
        op.create_table('clubs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('club_no', sa.String(length=20), nullable=False),
        sa.Column('club_name', sa.String(length=200), nullable=False),
        sa.Column('short_name', sa.String(length=100), nullable=True),
        sa.Column('district', sa.String(length=50), nullable=True),
        sa.Column('division', sa.String(length=50), nullable=True),
        sa.Column('area', sa.String(length=50), nullable=True),
        sa.Column('club_address', sa.Text(), nullable=True),
        sa.Column('meeting_date', sa.String(length=100), nullable=True),
        sa.Column('meeting_time', sa.Time(), nullable=True),
        sa.Column('contact_phone_number', sa.String(length=50), nullable=True),
        sa.Column('website', sa.String(length=255), nullable=True),
        sa.Column('logo_url', sa.String(length=255), nullable=True),
        sa.Column('founded_date', sa.Date(), nullable=True),
        sa.Column('current_excomm_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name='pk_clubs')
        )
        with op.batch_alter_table('clubs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_clubs_club_no'), ['club_no'], unique=True)

    if not inspector.has_table('pathways'):
        op.create_table('pathways',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.Column('abbr', sa.String(length=5), nullable=True),
        sa.Column('type', sa.String(length=20), nullable=True),
        sa.Column('status', sa.Enum('active', 'inactive', 'obsolete', name='pathway_status_enum'), nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk_pathways')
        )

    if not inspector.has_table('permissions'):
        op.create_table('permissions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(length=50), nullable=True),
        sa.Column('resource', sa.String(length=50), nullable=True),
        sa.Column('action', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id', name='pk_permissions')
        )
        with op.batch_alter_table('permissions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_permissions_category'), ['category'], unique=False)
            batch_op.create_index(batch_op.f('ix_permissions_name'), ['name'], unique=True)

    if not inspector.has_table('Users'):
        op.create_table('Users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('Username', sa.String(length=50), nullable=False),
        sa.Column('Email', sa.String(length=120), nullable=True),
        sa.Column('Pass_Hash', sa.String(length=255), nullable=False),
        sa.Column('Date_Created', sa.Date(), nullable=True),
        sa.Column('Status', sa.String(length=50), nullable=False, server_default='active'),
        sa.PrimaryKeyConstraint('id', name='pk_Users'),
        sa.UniqueConstraint('Email', name='unique_email'),
        sa.UniqueConstraint('Username', name='unique_username')
        )

    # verification_tasks removed (belongs to later migration)
    pass

    if not inspector.has_table('level_roles'):
        op.create_table('level_roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=255), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('count_required', sa.Integer(), nullable=False),
        sa.Column('band', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id', name='pk_level_roles')
        )

    # 2. Level 2 Tables (Dependencies on Base Tables)
    if not inspector.has_table('excomm'):
        op.create_table('excomm',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('club_id', sa.Integer(), nullable=False),
        sa.Column('excomm_term', sa.String(length=20), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('excomm_name', sa.String(length=100), nullable=True),
        sa.Column('president_id', sa.Integer(), nullable=True),
        sa.Column('vpe_id', sa.Integer(), nullable=True),
        sa.Column('vpm_id', sa.Integer(), nullable=True),
        sa.Column('vppr_id', sa.Integer(), nullable=True),
        sa.Column('secretary_id', sa.Integer(), nullable=True),
        sa.Column('treasurer_id', sa.Integer(), nullable=True),
        sa.Column('saa_id', sa.Integer(), nullable=True),
        sa.Column('ipp_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name='fk_excomm_club'),
        sa.ForeignKeyConstraint(['ipp_id'], ['Contacts.id'], name='fk_excomm_ipp_id_Contacts'),
        sa.ForeignKeyConstraint(['president_id'], ['Contacts.id'], name='fk_excomm_president_id_Contacts'),
        sa.ForeignKeyConstraint(['saa_id'], ['Contacts.id'], name='fk_excomm_saa_id_Contacts'),
        sa.ForeignKeyConstraint(['secretary_id'], ['Contacts.id'], name='fk_excomm_secretary_id_Contacts'),
        sa.ForeignKeyConstraint(['treasurer_id'], ['Contacts.id'], name='fk_excomm_treasurer_id_Contacts'),
        sa.ForeignKeyConstraint(['vpe_id'], ['Contacts.id'], name='fk_excomm_vpe_id_Contacts'),
        sa.ForeignKeyConstraint(['vpm_id'], ['Contacts.id'], name='fk_excomm_vpm_id_Contacts'),
        sa.ForeignKeyConstraint(['vppr_id'], ['Contacts.id'], name='fk_excomm_vppr_id_Contacts'),
        sa.PrimaryKeyConstraint('id', name='pk_excomm')
        )
        with op.batch_alter_table('excomm', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_excomm_excomm_term'), ['excomm_term'], unique=False)

    if not inspector.has_table('achievements'):
        op.create_table('achievements',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('contact_id', sa.Integer(), nullable=False),
        sa.Column('member_id', sa.String(length=50), nullable=True),
        sa.Column('issue_date', sa.Date(), nullable=False),
        sa.Column('achievement_type', sa.Enum('level-completion', 'path-completion', 'program-completion', name='achievement_type_enum'), nullable=False),
        sa.Column('path_name', sa.String(length=100), nullable=True),
        sa.Column('level', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], name='fk_achievements_contact_id_Contacts'),
        sa.PrimaryKeyConstraint('id', name='pk_achievements')
        )

    if not inspector.has_table('meeting_roles'):
        op.create_table('meeting_roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('icon', sa.String(length=50), nullable=True),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.Column('award_category', sa.String(length=30), nullable=True),
        sa.Column('needs_approval', sa.Boolean(), nullable=False),
        sa.Column('has_single_owner', sa.Boolean(), nullable=False),
        sa.Column('is_member_only', sa.Boolean(), nullable=True),
        sa.Column('club_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name='fk_meeting_roles_club_id_clubs'),
        sa.PrimaryKeyConstraint('id', name='pk_meeting_roles'),
        sa.UniqueConstraint('name', 'club_id', name='uq_meeting_role_name_club')
        )
        with op.batch_alter_table('meeting_roles', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_meeting_roles_club_id'), ['club_id'], unique=False)

    # messages removed (belongs to later migration)
    pass

    if not inspector.has_table('permission_audits'):
        op.create_table('permission_audits',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('admin_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('target_type', sa.String(length=50), nullable=False),
        sa.Column('target_id', sa.Integer(), nullable=False),
        sa.Column('target_name', sa.String(length=100), nullable=True),
        sa.Column('changes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['admin_id'], ['Users.id'], name='fk_permission_audits_admin_id_Users'),
        sa.PrimaryKeyConstraint('id', name='pk_permission_audits')
        )

    if not inspector.has_table('pathway_projects'):
        op.create_table('pathway_projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('path_id', sa.Integer(), nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=True),
        sa.Column('code', sa.String(length=10), nullable=True),
        sa.Column('level', sa.Integer(), nullable=True),
        sa.Column('type', sa.Enum('elective', 'required', 'other', name='pathway_project_type_enum'), nullable=False),
        sa.ForeignKeyConstraint(['path_id'], ['pathways.id'], name='fk_pathway_projects_path_id_pathways'),
        sa.ForeignKeyConstraint(['project_id'], ['Projects.id'], name='fk_pathway_projects_project_id_Projects'),
        sa.PrimaryKeyConstraint('id', name='pk_pathway_projects')
        )

    if not inspector.has_table('role_permissions'):
        op.create_table('role_permissions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('permission_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='fk_role_permissions_permission_id_permissions', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['role_id'], ['auth_roles.id'], name='fk_role_permissions_role_id_auth_roles', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='pk_role_permissions'),
        sa.UniqueConstraint('role_id', 'permission_id', name='unique_role_permission')
        )

    # 3. Level 3 Tables
    if not inspector.has_table('Meetings'):
        op.create_table('Meetings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('club_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=255), nullable=True),
        sa.Column('Meeting_Number', mysql.SMALLINT(unsigned=True), nullable=False),
        sa.Column('Meeting_Date', sa.Date(), nullable=True),
        sa.Column('Meeting_Title', sa.String(length=255), nullable=True),
        sa.Column('Subtitle', sa.String(length=255), nullable=True),
        sa.Column('Start_Time', sa.Time(), nullable=True),
        sa.Column('Meeting_Template', sa.String(length=100), nullable=True),
        sa.Column('WOD', sa.String(length=100), nullable=True),
        sa.Column('best_table_topic_id', sa.Integer(), nullable=True),
        sa.Column('best_evaluator_id', sa.Integer(), nullable=True),
        sa.Column('best_speaker_id', sa.Integer(), nullable=True),
        sa.Column('best_role_taker_id', sa.Integer(), nullable=True),
        sa.Column('media_id', sa.Integer(), nullable=True),
        sa.Column('ge_mode', sa.Integer(), nullable=True),
        sa.Column('status', sa.Enum('unpublished', 'not started', 'running', 'finished', 'cancelled', name='meeting_status'), nullable=False),
        sa.Column('nps', sa.Float(), nullable=True),
        sa.Column('manager_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['best_evaluator_id'], ['Contacts.id'], name='fk_Meetings_best_evaluator_id_Contacts'),
        sa.ForeignKeyConstraint(['best_role_taker_id'], ['Contacts.id'], name='fk_Meetings_best_role_taker_id_Contacts'),
        sa.ForeignKeyConstraint(['best_speaker_id'], ['Contacts.id'], name='fk_Meetings_best_speaker_id_Contacts'),
        sa.ForeignKeyConstraint(['best_table_topic_id'], ['Contacts.id'], name='fk_Meetings_best_table_topic_id_Contacts'),
        sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name='fk_Meetings_club_id_clubs'),
        sa.ForeignKeyConstraint(['manager_id'], ['Contacts.id'], name='fk_Meetings_manager_id_Contacts'),
        sa.PrimaryKeyConstraint('id', name='pk_Meetings'),
        sa.UniqueConstraint('Meeting_Number', name='uq_Meetings_Meeting_Number')
        )
        with op.batch_alter_table('Meetings', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_Meetings_club_id'), ['club_id'], unique=False)

    if not inspector.has_table('contact_clubs'):
        op.create_table('contact_clubs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('contact_id', sa.Integer(), nullable=False),
        sa.Column('club_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name='fk_contact_clubs_club_id_clubs', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], name='fk_contact_clubs_contact_id_Contacts', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='pk_contact_clubs'),
        sa.UniqueConstraint('contact_id', 'club_id', name='uq_contact_club')
        )

    if not inspector.has_table('Session_Types'):
        op.create_table('Session_Types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('Title', sa.String(length=255), nullable=False),
        sa.Column('Is_Section', sa.Boolean(), nullable=True),
        sa.Column('Is_Hidden', sa.Boolean(), nullable=True),
        sa.Column('Valid_for_Project', sa.Boolean(), nullable=True),
        sa.Column('Duration_Min', sa.Integer(), nullable=True),
        sa.Column('Duration_Max', sa.Integer(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.Column('club_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name='fk_Session_Types_club_id_clubs'),
        sa.ForeignKeyConstraint(['role_id'], ['meeting_roles.id'], name='fk_Session_Types_role_id_meeting_roles'),
        sa.PrimaryKeyConstraint('id', name='pk_Session_Types'),
        sa.UniqueConstraint('Title', 'club_id', name='uq_session_type_title_club')
        )

    if not inspector.has_table('roster'):
        op.create_table('roster',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('meeting_number', sa.Integer(), nullable=True),
        sa.Column('order_number', sa.Integer(), nullable=True),
        sa.Column('ticket_id', sa.Integer(), nullable=True),
        sa.Column('contact_id', sa.Integer(), nullable=True),
        sa.Column('contact_type', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], name='fk_roster_contact_id_Contacts'),
        sa.PrimaryKeyConstraint('id', name='pk_roster')
        )

    if not inspector.has_table('votes'):
        op.create_table('votes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('meeting_number', sa.Integer(), nullable=True),
        sa.Column('voter_identifier', sa.String(length=64), nullable=False),
        sa.Column('award_category', sa.Enum('speaker', 'evaluator', 'role-taker', 'table-topic', 'debater', name='award_category_enum'), nullable=True),
        sa.Column('contact_id', sa.Integer(), nullable=True),
        sa.Column('question', sa.String(length=255), nullable=True),
        sa.Column('score', sa.Integer(), nullable=True),
        sa.Column('comments', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], name='fk_votes_contact_id_Contacts'),
        sa.PrimaryKeyConstraint('id', name='pk_votes')
        )
        with op.batch_alter_table('votes', schema=None) as batch_op:
            batch_op.create_index('idx_meeting_voter', ['meeting_number', 'voter_identifier'], unique=False)

    if not inspector.has_table('Session_Logs'):
        op.create_table('Session_Logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('Meeting_Number', mysql.SMALLINT(unsigned=True), nullable=True),
        sa.Column('Meeting_Seq', sa.Integer(), nullable=True),
        sa.Column('Session_Title', sa.String(length=255), nullable=True),
        sa.Column('Type_ID', sa.Integer(), nullable=False),
        sa.Column('hidden', sa.Boolean(), nullable=True),
        sa.Column('Project_ID', sa.Integer(), nullable=True),
        sa.Column('Start_Time', sa.Time(), nullable=True),
        sa.Column('Duration_Min', sa.Integer(), nullable=True),
        sa.Column('Duration_Max', sa.Integer(), nullable=True),
        sa.Column('Notes', sa.String(length=1000), nullable=True),
        sa.Column('Status', sa.String(length=50), nullable=True),
        sa.Column('state', sa.String(length=50), nullable=False, server_default='pending'),
        sa.Column('project_code', sa.String(length=10), nullable=True),
        sa.Column('pathway', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['Project_ID'], ['Projects.id'], name='fk_Session_Logs_Project_ID_Projects'),
        sa.ForeignKeyConstraint(['Type_ID'], ['Session_Types.id'], name='fk_Session_Logs_Type_ID_Session_Types'),
        sa.ForeignKeyConstraint(['Meeting_Number'], ['Meetings.Meeting_Number'], name='fk_Session_Logs_Meeting_Number_Meetings'),
        sa.PrimaryKeyConstraint('id', name='pk_Session_Logs')
        )

    if not inspector.has_table('Media'):
        op.create_table('Media',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('log_id', sa.Integer(), nullable=True),
        sa.Column('url', sa.String(length=1024), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['log_id'], ['Session_Logs.id'], name='fk_Media_log_id_Session_Logs', ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id', name='pk_Media')
        )

    if not inspector.has_table('waitlists'):
        op.create_table('waitlists',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_log_id', sa.Integer(), nullable=False),
        sa.Column('contact_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], name='fk_waitlists_contact_id_Contacts'),
        sa.ForeignKeyConstraint(['session_log_id'], ['Session_Logs.id'], name='fk_waitlists_session_log_id_Session_Logs'),
        sa.PrimaryKeyConstraint('id', name='pk_waitlists')
        )

    # Now add the FK from clubs to excomm if it doesn't exist
    inspector = Inspector.from_engine(conn) 
    clubs_fks = inspector.get_foreign_keys('clubs')
    has_excomm_fk = any('current_excomm_id' in fk.get('constrained_columns', []) and fk.get('referred_table') == 'excomm' for fk in clubs_fks)
    
    if not has_excomm_fk:
        with op.batch_alter_table('clubs', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_clubs_current_excomm_id', 'excomm', ['current_excomm_id'], ['id'])

    # Default Data Seeding
    res = conn.execute(sa.text("SELECT id FROM clubs WHERE id=1")).fetchone()
    if not res:
        conn.execute(sa.text("INSERT INTO clubs (id, club_no, club_name) VALUES (1, '0000000', 'Default Club')"))

    # Permission Seeding
    from datetime import datetime, timezone
    new_perms = [
        {'name': 'ABOUT_CLUB_VIEW', 'description': 'View club info', 'category': 'club', 'resource': 'club', 'action': 'view'},
        {'name': 'ABOUT_CLUB_EDIT', 'description': 'Edit club info', 'category': 'club', 'resource': 'club', 'action': 'edit'},
        {'name': 'ROSTER_EDIT', 'description': 'Edit club roster', 'category': 'club', 'resource': 'roster', 'action': 'edit'},
        {'name': 'LUCKY_DRAW_VIEW', 'description': 'View lucky draw', 'category': 'club', 'resource': 'lucky_draw', 'action': 'view'},
        {'name': 'LUCKY_DRAW_EDIT', 'description': 'Edit lucky draw', 'category': 'club', 'resource': 'lucky_draw', 'action': 'edit'}
    ]
    
    for perm in new_perms:
        existing = conn.execute(sa.text("SELECT id FROM permissions WHERE name = :name"), {'name': perm['name']}).fetchone()
        if not existing:
            conn.execute(sa.text("INSERT INTO permissions (name, description, category, resource, action, created_at) VALUES (:name, :description, :category, :resource, :action, :created_at)"),
                {**perm, 'created_at': datetime.now(timezone.utc)})

    # ### end Alembic commands ###


def downgrade():
    # Two-phase cleanup to handle circular dependencies and strict MySQL 8.0+ checks
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    
    # 1. Disable FK checks for data
    conn.execute(sa.text("SET FOREIGN_KEY_CHECKS = 0;"))
    
    # 2. Phase 1: Drop all Foreign Keys
    for table in tables:
        fks = inspector.get_foreign_keys(table)
        if fks:
            with op.batch_alter_table(table, schema=None) as batch_op:
                for fk in fks:
                    try:
                        batch_op.drop_constraint(fk['name'], type_='foreignkey')
                    except Exception as e:
                        print(f"Skipping FK drop for {fk['name']} on {table}: {e}")

    # 3. Phase 2: Drop all Tables
    # Use the inspector to drop EVERY table found in the database
    for table_name in inspector.get_table_names():
        if table_name != 'alembic_version':
            op.execute(sa.text(f"DROP TABLE IF EXISTS `{table_name}`"))
        
    conn.execute(sa.text("SET FOREIGN_KEY_CHECKS = 1;"))
