"""first deployment with backup data 20260116

Revision ID: e64ca3cd6a87
Revises: 
Create Date: 2026-01-16 19:11:20.364578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = 'e64ca3cd6a87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if 'clubs' not in tables:
        # Create clubs table without FK to excomm initially to avoid circular dependency
        op.create_table('clubs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('club_no', sa.String(length=20), nullable=False),
        sa.Column('club_name', sa.String(length=200), nullable=False),
        sa.Column('short_name', sa.String(length=100), nullable=True),
        sa.Column('district', sa.String(length=50), nullable=True),
        sa.Column('division', sa.String(length=50), nullable=True),
        sa.Column('area', sa.String(length=50), nullable=True),
        sa.Column('club_address', sa.Text(), nullable=True),
        sa.Column('meeting_date', sa.String(length=100), nullable=True),
        sa.Column('meeting_time', sa.Time(), nullable=True),
        sa.Column('contact_phone_number', sa.String(length=50), nullable=True),
        sa.Column('website', sa.String(length=255), nullable=True),
        sa.Column('founded_date', sa.Date(), nullable=True),
        sa.Column('current_excomm_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        # Removed FK to excomm here
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('clubs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_clubs_club_no'), ['club_no'], unique=True)
            
    # Ensure default club exists regardless of whether table was just created
    # Use raw connection to check and insert
    conn = op.get_bind()
    res = conn.execute(sa.text("SELECT id FROM clubs WHERE id=1")).fetchone()
    if not res:
        conn.execute(sa.text("INSERT INTO clubs (id, club_no, club_name) VALUES (1, '0000000', 'Default Club')"))

    if 'excomm' not in tables:
        op.create_table('excomm',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('club_id', sa.Integer(), nullable=False),
        sa.Column('excomm_term', sa.String(length=20), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('excomm_name', sa.String(length=100), nullable=True),
        sa.Column('president_id', sa.Integer(), nullable=True),
        sa.Column('vpe_id', sa.Integer(), nullable=True),
        sa.Column('vpm_id', sa.Integer(), nullable=True),
        sa.Column('vppr_id', sa.Integer(), nullable=True),
        sa.Column('secretary_id', sa.Integer(), nullable=True),
        sa.Column('treasurer_id', sa.Integer(), nullable=True),
        sa.Column('saa_id', sa.Integer(), nullable=True),
        sa.Column('ipp_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
        sa.ForeignKeyConstraint(['ipp_id'], ['Contacts.id'], ),
        sa.ForeignKeyConstraint(['president_id'], ['Contacts.id'], ),
        sa.ForeignKeyConstraint(['saa_id'], ['Contacts.id'], ),
        sa.ForeignKeyConstraint(['secretary_id'], ['Contacts.id'], ),
        sa.ForeignKeyConstraint(['treasurer_id'], ['Contacts.id'], ),
        sa.ForeignKeyConstraint(['vpe_id'], ['Contacts.id'], ),
        sa.ForeignKeyConstraint(['vpm_id'], ['Contacts.id'], ),
        sa.ForeignKeyConstraint(['vppr_id'], ['Contacts.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('excomm', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_excomm_excomm_term'), ['excomm_term'], unique=False)

    # Now add the FK from clubs to excomm if it doesn't exist
    # Re-fetch inspector to get latest schema
    inspector = Inspector.from_engine(conn) 
    clubs_fks = inspector.get_foreign_keys('clubs')
    has_excomm_fk = False
    for fk in clubs_fks:
        if 'current_excomm_id' in fk.get('constrained_columns', []) and fk.get('referred_table') == 'excomm':
             has_excomm_fk = True
             break
    
    if not has_excomm_fk:
        with op.batch_alter_table('clubs', schema=None) as batch_op:
            batch_op.create_foreign_key('fk_clubs_current_excomm_id', 'excomm', ['current_excomm_id'], ['id'])

    if 'contact_clubs' not in tables:
        op.create_table('contact_clubs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('contact_id', sa.Integer(), nullable=False),
        sa.Column('club_id', sa.Integer(), nullable=False),
        sa.Column('membership_type', sa.String(length=50), nullable=True),
        sa.Column('joined_date', sa.Date(), nullable=True),
        sa.Column('is_primary', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('contact_id', 'club_id', name='uq_contact_club')
        )
        with op.batch_alter_table('contact_clubs', schema=None) as batch_op:
            batch_op.create_index('ix_contact_clubs_club', ['club_id'], unique=False)
            batch_op.create_index('ix_contact_clubs_contact', ['contact_id'], unique=False)

    columns = [c['name'] for c in inspector.get_columns('Meetings')]
    if 'club_id' not in columns:
        with op.batch_alter_table('Meetings', schema=None) as batch_op:
            batch_op.add_column(sa.Column('club_id', sa.Integer(), nullable=False, server_default='1'))
            batch_op.create_index(batch_op.f('ix_Meetings_club_id'), ['club_id'], unique=False)
            batch_op.create_foreign_key('fk_meetings_club_id', 'clubs', ['club_id'], ['id'])
    else:
        # Check if FK missing even if column exists
        meetings_fks = inspector.get_foreign_keys('Meetings')
        fk_found = False
        for fk in meetings_fks:
            if 'club_id' in fk.get('constrained_columns', []) and fk.get('referred_table') == 'clubs':
                fk_found = True
                break
        if not fk_found:
             # Ensure existing nulls or invalid values are fixed before adding FK
             # Update club_id to 1 if it is 0 or null (safeguard)
             op.execute("UPDATE Meetings SET club_id = 1 WHERE club_id IS NULL OR club_id = 0")
             with op.batch_alter_table('Meetings', schema=None) as batch_op:
                batch_op.create_foreign_key('fk_meetings_club_id', 'clubs', ['club_id'], ['id'])

    # ### end Alembic commands ###

    # --- Custom Data Seeding: Permissions ---
    # Ensure ABOUT_CLUB permissions exist and are assigned
    from datetime import datetime, timezone
    
    # Use raw connection for data manipulation to rely less on models
    conn = op.get_bind()
    
    # Define permissions to add
    new_perms = [
        {
            'name': 'ABOUT_CLUB_VIEW',
            'description': 'View club information and executive committee',
            'category': 'club',
            'resource': 'club',
            'action': 'view'
        },
        {
            'name': 'ABOUT_CLUB_EDIT',
            'description': 'Edit club information and executive committee',
            'category': 'club',
            'resource': 'club',
            'action': 'edit'
        },
        {
            'name': 'ROSTER_EDIT',
            'description': 'Edit club roster',
            'category': 'club',
            'resource': 'roster',
            'action': 'edit'
        },
        {
            'name': 'LUCKY_DRAW_VIEW',
            'description': 'View lucky draw',
            'category': 'club',
            'resource': 'lucky_draw',
            'action': 'view'
        },
        {
            'name': 'LUCKY_DRAW_EDIT',
            'description': 'Edit lucky draw',
            'category': 'club',
            'resource': 'lucky_draw',
            'action': 'edit'
        }
    ]
    
    for perm in new_perms:
        # Check if permission exists
        existing = conn.execute(sa.text("SELECT id FROM permissions WHERE name = :name"), {'name': perm['name']}).fetchone()
        if not existing:
            conn.execute(
                sa.text("""
                    INSERT INTO permissions (name, description, category, resource, action, created_at) 
                    VALUES (:name, :description, :category, :resource, :action, :created_at)
                """),
                {
                    'name': perm['name'],
                    'description': perm['description'],
                    'category': perm['category'],
                    'resource': perm['resource'],
                    'action': perm['action'],
                    'created_at': datetime.now(timezone.utc)
                }
            )

    # Re-fetch permission IDs
    perm_map = {}
    rows = conn.execute(sa.text("SELECT id, name FROM permissions WHERE name LIKE 'ABOUT_CLUB_%'")).fetchall()
    for row in rows:
        # row is (id, name)
        perm_map[row[1]] = row[0]
        
    # Fetch Role IDs
    role_map = {}
    rows = conn.execute(sa.text("SELECT id, name FROM auth_roles")).fetchall()
    for row in rows:
        role_map[row[1]] = row[0]
        
    # Define assignments: (RoleName, PermissionName)
    assignments = [
        ('SysAdmin', 'ABOUT_CLUB_VIEW'),
        ('ClubAdmin', 'ABOUT_CLUB_VIEW'),
        ('Staff', 'ABOUT_CLUB_VIEW'),
        ('User', 'ABOUT_CLUB_VIEW'),
        ('SysAdmin', 'ABOUT_CLUB_EDIT'),
        ('ClubAdmin', 'ABOUT_CLUB_EDIT'),
        ('SysAdmin', 'ROSTER_EDIT'),
        ('ClubAdmin', 'ROSTER_EDIT'),
        ('SysAdmin', 'LUCKY_DRAW_VIEW'),
        ('ClubAdmin', 'LUCKY_DRAW_VIEW'),
        ('Staff', 'LUCKY_DRAW_VIEW'),
        ('User', 'LUCKY_DRAW_VIEW'),
        ('SysAdmin', 'LUCKY_DRAW_EDIT'),
        ('ClubAdmin', 'LUCKY_DRAW_EDIT')
    ]
    
    for role_name, perm_name in assignments:
        if role_name in role_map and perm_name in perm_map:
            rid = role_map[role_name]
            pid = perm_map[perm_name]
            
            # Check if assignment exists
            exists = conn.execute(
                sa.text("SELECT 1 FROM role_permissions WHERE role_id = :rid AND permission_id = :pid"),
                {'rid': rid, 'pid': pid}
            ).fetchone()
            
            if not exists:
                conn.execute(
                    sa.text("INSERT INTO role_permissions (role_id, permission_id) VALUES (:rid, :pid)"),
                    {'rid': rid, 'pid': pid}
                )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    columns = [c['name'] for c in inspector.get_columns('Meetings')]
    if 'club_id' in columns:
        # Dynamically find FK name to drop it safely
        meetings_fks = inspector.get_foreign_keys('Meetings')
        fk_name = None
        for fk in meetings_fks:
             if 'club_id' in fk.get('constrained_columns', []) and fk.get('referred_table') == 'clubs':
                 fk_name = fk['name']
                 break
        
        with op.batch_alter_table('Meetings', schema=None) as batch_op:
            if fk_name:
                batch_op.drop_constraint(fk_name, type_='foreignkey')
            # Assuming index exists if column exists, but could also inspect indexes if paranoid.
            # Alembic drop_index might fail if index missing, but let's assume standard alembic naming matches.
            try:
                batch_op.drop_index(batch_op.f('ix_Meetings_club_id'))
            except:
                pass # Ignore if index missing (not ideal but practical for cleanup)
                
            batch_op.drop_column('club_id')

    if 'contact_clubs' in tables:
        op.drop_table('contact_clubs')

    if 'user_clubs' in tables:
        op.drop_table('user_clubs')

    # Dropping excomm might fail if clubs refers to it.
    # So we should drop FK from clubs first.
        
    # Check clubs FKs
    if 'clubs' in tables:
        clubs_fks = inspector.get_foreign_keys('clubs')
        for fk in clubs_fks:
            if fk.get('referred_table') == 'excomm':
                with op.batch_alter_table('clubs', schema=None) as batch_op:
                    batch_op.drop_constraint(fk['name'], type_='foreignkey')

    if 'excomm' in tables:
        op.drop_table('excomm')

    if 'clubs' in tables:
        indexes = [i['name'] for i in inspector.get_indexes('clubs')]
        with op.batch_alter_table('clubs', schema=None) as batch_op:
            if 'ix_clubs_club_no' in indexes:
                batch_op.drop_index(batch_op.f('ix_clubs_club_no'))

        op.drop_table('clubs')
    # ### end Alembic commands ###

    # --- Custom Data Cleanup: Permissions ---
    # Remove the ABOUT_CLUB permissions created in upgrade
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM permissions WHERE name IN ('ABOUT_CLUB_VIEW', 'ABOUT_CLUB_EDIT', 'ROSTER_EDIT', 'LUCKY_DRAW_VIEW', 'LUCKY_DRAW_EDIT')"))
