"""Add contact_paths table

Revision ID: e6a9da78bcff
Revises: b386d5c209e9
Create Date: 2026-05-21 00:32:37.609999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6a9da78bcff'
down_revision = 'b386d5c209e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('registered_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], name=op.f('fk_contact_paths_contact_id_Contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['pathways.id'], name=op.f('fk_contact_paths_path_id_pathways'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_paths')),
    sa.UniqueConstraint('contact_id', 'path_id', name='uq_contact_path')
    )
    with op.batch_alter_table('contact_paths', schema=None) as batch_op:
        batch_op.create_index('ix_contact_paths_contact', ['contact_id'], unique=False)
        batch_op.create_index('ix_contact_paths_pathway', ['path_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_paths', schema=None) as batch_op:
        batch_op.drop_index('ix_contact_paths_pathway')
        batch_op.drop_index('ix_contact_paths_contact')

    op.drop_table('contact_paths')
    # ### end Alembic commands ###
