"""Add contact_type to Roster

Revision ID: ea9351d03692
Revises: 46d381bcd6b9
Create Date: 2025-12-28 21:55:01.000857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea9351d03692'
down_revision = '46d381bcd6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster', schema=None) as batch_op:
        batch_op.drop_column('contact_type')

    # ### end Alembic commands ###
