"""Rename Credential column to credentials in Users table

Revision ID: ed431c6389e2
Revises: ecf2689acb6b
Create Date: 2025-11-26 10:15:51.602787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed431c6389e2'
down_revision = 'ecf2689acb6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('Credential', 
                              new_column_name='credentials',
                              existing_type=sa.String(10),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('credentials',
                              new_column_name='Credential',
                              existing_type=sa.String(10),
                              nullable=True)

    # ### end Alembic commands ###