"""drop user_id from session_logs

Revision ID: f0145f9f8559
Revises: e2989f057059
Create Date: 2026-01-17 02:45:43.768837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0145f9f8559'
down_revision = 'e2989f057059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the index exists before trying to drop it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx['name'] for idx in inspector.get_indexes('Session_Logs')]
    columns = [col['name'] for col in inspector.get_columns('Session_Logs')]
    
    # Drop foreign keys on user_id first
    fks = inspector.get_foreign_keys('Session_Logs')
    user_id_fks = [fk['name'] for fk in fks if 'user_id' in fk.get('constrained_columns', [])]
    
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        for fk in user_id_fks:
            batch_op.drop_constraint(fk, type_='foreignkey')

        # Only drop the index if it exists
        if 'fk_session_logs_user' in indexes:
            batch_op.drop_index('fk_session_logs_user')
        
        # Only drop the column if it exists
        if 'user_id' in columns:
            batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index('fk_session_logs_user', ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_session_logs_user', 'Users', ['user_id'], ['id'])

    # ### end Alembic commands ###
