"""drop user_id from session_logs

Revision ID: f0145f9f8559
Revises: e2989f057059
Create Date: 2026-01-17 02:45:43.768837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0145f9f8559'
down_revision = 'e2989f057059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.drop_index('fk_session_logs_user')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index('fk_session_logs_user', ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_session_logs_user', 'Users', ['user_id'], ['id'])

    # ### end Alembic commands ###
