"""Remove profile columns from User model

Revision ID: f0617785810c
Revises: a74d17f36522
Create Date: 2025-12-26 12:53:30.987245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0617785810c'
down_revision = 'a74d17f36522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Unrelated changes removed to avoid conflicts
    # with op.batch_alter_table('Meetings', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
    #     batch_op.drop_column('ID')

    # with op.batch_alter_table('Projects', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
    #     batch_op.drop_column('ID')

    # with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('fk_project'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'Projects', ['Project_ID'], ['id'])

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Member_ID'))
        batch_op.drop_constraint(batch_op.f('fk_mentor_contact'), type_='foreignkey')
        batch_op.drop_column('Mentor_ID')
        batch_op.drop_column('Member_ID')
        batch_op.drop_column('Next_Project')
        batch_op.drop_column('Current_Path')
        batch_op.drop_column('credentials')

    # with op.batch_alter_table('pathway_projects', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('pathway_projects_ibfk_2'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'Projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pathway_projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pathway_projects_ibfk_2'), 'Projects', ['project_id'], ['ID'])

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credentials', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('Current_Path', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('Next_Project', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('Member_ID', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('Mentor_ID', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_mentor_contact'), 'Contacts', ['Mentor_ID'], ['id'])
        batch_op.create_index(batch_op.f('Member_ID'), ['Member_ID'], unique=True)

    with op.batch_alter_table('Session_Logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_project'), 'Projects', ['Project_ID'], ['ID'])

    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('Meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
