"""refactor excomm to use association table

Revision ID: f0ab859c9cc1
Revises: 65bc969cc9a2
Create Date: 2026-02-02 11:21:08.830542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0ab859c9cc1'
down_revision = '65bc969cc9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excomm_officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('excomm_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('meeting_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], name=op.f('fk_excomm_officers_contact_id_Contacts')),
    sa.ForeignKeyConstraint(['excomm_id'], ['excomm.id'], name=op.f('fk_excomm_officers_excomm_id_excomm')),
    sa.ForeignKeyConstraint(['meeting_role_id'], ['meeting_roles.id'], name=op.f('fk_excomm_officers_meeting_role_id_meeting_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_excomm_officers')),
    sa.UniqueConstraint('excomm_id', 'meeting_role_id', name='uq_excomm_role')
    )
    with op.batch_alter_table('excomm', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_excomm_vpm_id_Contacts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_excomm_saa_id_Contacts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_excomm_ipp_id_Contacts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_excomm_treasurer_id_Contacts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_excomm_vpe_id_Contacts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_excomm_vppr_id_Contacts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_excomm_president_id_Contacts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_excomm_secretary_id_Contacts'), type_='foreignkey')
        batch_op.drop_column('vpm_id')
        batch_op.drop_column('treasurer_id')
        batch_op.drop_column('vppr_id')
        batch_op.drop_column('president_id')
        batch_op.drop_column('ipp_id')
        batch_op.drop_column('vpe_id')
        batch_op.drop_column('saa_id')
        batch_op.drop_column('secretary_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('excomm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secretary_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('saa_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vpe_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ipp_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('president_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vppr_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('treasurer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vpm_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_excomm_secretary_id_Contacts'), 'Contacts', ['secretary_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_excomm_president_id_Contacts'), 'Contacts', ['president_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_excomm_vppr_id_Contacts'), 'Contacts', ['vppr_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_excomm_vpe_id_Contacts'), 'Contacts', ['vpe_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_excomm_treasurer_id_Contacts'), 'Contacts', ['treasurer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_excomm_ipp_id_Contacts'), 'Contacts', ['ipp_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_excomm_saa_id_Contacts'), 'Contacts', ['saa_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_excomm_vpm_id_Contacts'), 'Contacts', ['vpm_id'], ['id'])

    op.drop_table('excomm_officers')
    # ### end Alembic commands ###
