"""add permanent deletion flags to messages

Revision ID: f33ed556dffb
Revises: 2930134a6e92
Create Date: 2026-06-12 00:19:58.287525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f33ed556dffb'
down_revision = '2930134a6e92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permanently_deleted_by_sender', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('permanently_deleted_by_recipient', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('permanently_deleted_by_recipient')
        batch_op.drop_column('permanently_deleted_by_sender')
    # ### end Alembic commands ###
