"""Add roster_roles junction table for many-to-many relationship

Revision ID: f6c80eb1b7bb
Revises: e4b40623ff55
Create Date: 2026-01-12 16:53:07.518686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c80eb1b7bb'
down_revision = 'e4b40623ff55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roster_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['roster.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roster_id', 'role_id', name='uq_roster_role')
    )
    op.create_table('waitlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_log_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['session_log_id'], ['Session_Logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waitlists')
    op.drop_table('roster_roles')
    # ### end Alembic commands ###
