"""add club modules table

Revision ID: f72f66fd02cf
Revises: c1d2e3f4a5b6
Create Date: 2026-06-05 17:45:34.430837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72f66fd02cf'
down_revision = 'c1d2e3f4a5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_modules_club_id_clubs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_modules')),
    sa.UniqueConstraint('club_id', 'module_name', name='uq_club_module')
    )
    with op.batch_alter_table('club_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_club_modules_club_id'), ['club_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_club_modules_club_id'))

    op.drop_table('club_modules')
    # ### end Alembic commands ###
