"""add club_id to achievements

Revision ID: f78bbc878a49
Revises: 07c3adfd0a6a
Create Date: 2026-02-12 23:32:48.784924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78bbc878a49'
down_revision = '07c3adfd0a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_achievements_club_id'), ['club_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_achievements_club_id_clubs'), 'clubs', ['club_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_achievements_club_id_clubs'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_achievements_club_id'))
        batch_op.drop_column('club_id')

    # ### end Alembic commands ###
