"""centralize_achievements_v2

Revision ID: f9af03b411b2
Revises: 500298c83850
Create Date: 2026-02-27 23:06:24.473326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9af03b411b2'
down_revision = '500298c83850'
branch_labels = None
depends_on = None


def upgrade():
    from sqlalchemy.engine.reflection import Inspector
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = inspector.get_columns('achievements')
    column_names = [col['name'] for col in columns]
    fks = inspector.get_foreign_keys('achievements')
    fk_names = [fk['name'] for fk in fks]

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        if 'user_id' not in column_names:
            batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        if 'requestor_id' not in column_names:
            batch_op.add_column(sa.Column('requestor_id', sa.Integer(), nullable=True))
        
        if 'contact_id' in column_names:
            batch_op.alter_column('contact_id',
                   existing_type=mysql.INTEGER(),
                   nullable=True)
        
        if 'fk_achievements_requestor_id_users' not in fk_names:
            batch_op.create_foreign_key(batch_op.f('fk_achievements_requestor_id_users'), 'users', ['requestor_id'], ['id'])
        if 'fk_achievements_user_id_users' not in fk_names:
            batch_op.create_foreign_key(batch_op.f('fk_achievements_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_achievements_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_achievements_requestor_id_users'), type_='foreignkey')
        batch_op.alter_column('contact_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('requestor_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
