"""rename_roles_table_to_meeting_roles

Revision ID: fa4966cc4756
Revises: daec7f3551bf
Create Date: 2026-01-15 17:07:22.089818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa4966cc4756'
down_revision = 'daec7f3551bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('roles', 'meeting_roles')
    
    with op.batch_alter_table('Session_Types', schema=None) as batch_op:
        batch_op.drop_constraint('Session_Types_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'meeting_roles', ['role_id'], ['id'])

    with op.batch_alter_table('roster_roles', schema=None) as batch_op:
        batch_op.drop_constraint('roster_roles_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'meeting_roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roster_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('roster_roles_ibfk_1', 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('Session_Types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Session_Types_ibfk_1', 'roles', ['role_id'], ['id'])

    op.rename_table('meeting_roles', 'roles')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
