"""add upload links table

Revision ID: fd62535f1761
Revises: 9023be6a588b
Create Date: 2026-05-27 16:50:07.132845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd62535f1761'
down_revision = '9023be6a588b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_files', sa.Integer(), nullable=True),
    sa.Column('max_file_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_upload_links_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_upload_links_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['Meetings.id'], name=op.f('fk_upload_links_meeting_id_Meetings'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_links'))
    )
    with op.batch_alter_table('upload_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_links_club_id'), ['club_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_links_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_upload_links_meeting_id'), ['meeting_id'], unique=False)
    # ### end Alembic commands ###

    from datetime import datetime, timezone
    conn = op.get_bind()

    # 1. Add FILE_UPLOAD_MANAGE permission
    existing = conn.execute(
        sa.text("SELECT id FROM permissions WHERE name = 'FILE_UPLOAD_MANAGE'")
    ).fetchone()
    if not existing:
        conn.execute(
            sa.text("""
                INSERT INTO permissions (name, description, category, resource, action, created_at)
                VALUES ('FILE_UPLOAD_MANAGE',
                        'Manage upload links and retrieve files',
                        'club', 'file_upload', 'manage', :created_at)
            """),
            {'created_at': datetime.now(timezone.utc)}
        )

    # 2. Grant to ClubAdmin and Operator roles
    perm_row = conn.execute(
        sa.text("SELECT id FROM permissions WHERE name = 'FILE_UPLOAD_MANAGE'")
    ).fetchone()
    if not perm_row:
        return

    pid = perm_row[0]

    for role_name in ('ClubAdmin', 'Operator'):
        role_row = conn.execute(
            sa.text("SELECT id FROM auth_roles WHERE name = :name"),
            {'name': role_name}
        ).fetchone()

        if role_row:
            rid = role_row[0]
            exists = conn.execute(
                sa.text("SELECT 1 FROM role_permissions WHERE role_id = :rid AND permission_id = :pid"),
                {'rid': rid, 'pid': pid}
            ).fetchone()

            if not exists:
                conn.execute(
                    sa.text("INSERT INTO role_permissions (role_id, permission_id) VALUES (:rid, :pid)"),
                    {'rid': rid, 'pid': pid}
                )


def downgrade():
    conn = op.get_bind()
    perm_row = conn.execute(
        sa.text("SELECT id FROM permissions WHERE name = 'FILE_UPLOAD_MANAGE'")
    ).fetchone()
    if perm_row:
        pid = perm_row[0]
        conn.execute(
            sa.text("DELETE FROM role_permissions WHERE permission_id = :pid"),
            {'pid': pid}
        )
    conn.execute(
        sa.text("DELETE FROM permissions WHERE name = 'FILE_UPLOAD_MANAGE'")
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_links_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_upload_links_code'))
        batch_op.drop_index(batch_op.f('ix_upload_links_club_id'))

    op.drop_table('upload_links')
    # ### end Alembic commands ###
